### ISSUE TITLE
Yahoo data sometimes fails to get -- "query.results.channel is null or not an object"

### ISSUE THREAD

**Issue by samuelatlarge** [monkeecreate/jquery.simpleWeather#101]
First: I love your library! It's been an incredibly smooth addition to our company intranet. Thank you.

My issue: Occasionally my SimpleWeather widget fails to load on Internet Explorer 8. It happens maybe once out of every 10 page loads. When it does fail, the DOM element is rendered and the browser looks like it's waiting on data. A few seconds go by, then IE8 reports the error "query.results.channel is null or not an object"

I'm in an enterprise environment where some domains are blocked, and though it's possible that's the issue, we've added query.yahooapis.com to the company whitelist. Does this sound like a potential issue with the script, IE 8 compatibility or Yahoo's weather service? 

JSFiddle of the widget as implemented here: http://jsfiddle.net/cK3nZ/1/

**Comment by hallmatt** [comment]
Has this fix been implemented?

**Comment by oasif** [comment]
to fix edit jquery.simpleWeather.js
remove
and gflags="R" limit 1 
from line 26

or remove the above string from jquery.simpleWeather.min.js

**Comment by Chimit** [comment]
@oasif thank you very much! It works!

**Comment by JWiersema** [comment]
Oasif solution doesn't work for me, or am I doing it wrong?
I changed
(select woeid from geo.placefinder where text="'+i.location+'" and gflags="R" limit 1)
to
(select woeid from geo.placefinder where text="'+i.location+'")
There is no issue with yahoo connectivity because when i use the request url the script compiles i get the correct data back. Please investigate further and let us know a solution.

**Comment by oasif** [comment]
The following line 26 should work with zip code:
weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="'+options.location+'") and u="'+options.unit+'"';

**Comment by ejanus** [comment]
Oasif's solution worked for me.  But, I hope there is a better solutions soon.

**Comment by Chimit** [comment]
The problem came back again after removing `and gflags="R" limit 1`.

`Uncaught TypeError: Cannot read property 'channel' of null`

**Comment by AbdullahKharam** [comment]
Seems the website https://s.yimg.com/ that .js plugin is refering does not work.
"Yahoo Logo
Will be right back...

Thank you for your patience.
Our engineers are working quickly to resolve the issue."

**Comment by fleeting** [comment]
See #174 for info and temp fixes..

**Comment by fleeting** [comment]
This is fixed in `v3.1.0`.

**Comment by biapar** [comment]
Ok. It works now.

**Comment by BTMouseKing** [comment]
@fleeting the fix in v3.1.0 added a friendly error message but sometimes it shows up, i'm just checking the example in http://simpleweatherjs.com/ , is it because the Yahoo weather api is unstable?

**Comment by fleeting** [comment]
@BTMouseKing The error messages shows up on the demo directly - http://codepen.io/fleeting/pen/xklfq. It just doesn't seem to show up on the embedded version for some reason.

**Comment by BTMouseKing** [comment]
Yeah, i also used https://developer.yahoo.com/weather/ to test the api but seems a bit unstable, thanks for confirming.

**Comment by chakAs3** [comment]
it is not stable at all even on the demo website the result = null sometimes ( often )
