### ISSUE TITLE
Issue when used in cordova

### ISSUE THREAD

**Issue by vamsikollipara** [monkeecreate/jquery.simpleWeather#119]
hi,

Simple weather, its really working nice when i run it in the webpage, But what i need is a android app. I'm building one with cordova. it is not working. Can any one help me. I'm in desperate need of it.

**Comment by jpeskin** [comment]
I found that it worked on iOS as long as I setup suitable access rules as Cordova blocks non-local URLs by default.  While under development, some simple blanket rules that will open up access can go in your Cordova config.xml:
```
<access origin="http://*"/>
<access origin="https://*"/>
```
