### ISSUE TITLE
Animated weather icons?

### ISSUE THREAD

**Issue by aaronhb** [monkeecreate/jquery.simpleWeather#121]
Anyone have any luck using animated weather icons or for the Skycons that http://forecast.io/ uses?

Great plugin!!!

**Comment by noxbriones** [comment]
+1 for this. Lovi'n his plugin!

**Comment by fleeting** [comment]
This has been possible as you can use any weather icons you want, just match them up with the weather codes. You can use any icons, animated icons, or an icon font. See the docs for a little more detail or this demo which uses a weather font. http://codepen.io/fleeting/pen/xklfq
