### ISSUE TITLE
Make Geological Demo Automatically Use Location

### ISSUE THREAD

**Issue by jmiller1225** [monkeecreate/jquery.simpleWeather#122]
Hi,
  I have one issue I'm trying to figure out.  More so, I'm not that great with this kind of coding,  I was just wondering if there is any way I can have it automatically load the weather for the users location and possibly make a link to there 5 day forecast?

**Comment by fleeting** [comment]
Here is a quick example that will try to automatically load weather based on the users location http://codepen.io/fleeting/pen/yyKerv. A few things to note though; the user still has to allow your site to use their location so it won't load until they allow it, you should check if a user declines to share their location, and should also account for if a user never notices the location share prompt and ignores it.
