### ISSUE TITLE
Is there an alt.time to change from 12hr to 24hr format?

### ISSUE THREAD

**Issue by isaachinman** [monkeecreate/jquery.simpleWeather#124]
As stated in the title, I'm looking for a way to output 24hr format times instead of 12hr. I am attempting to have a function where something happens if the current time falls between sunset and sunrise, else something else happens.

**Comment by fleeting** [comment]
Not currently. The API just returns 12 hour format so that's what I pass along. There are ways to convert 12 hour to 24 hour in JavaScript so you might look into them. If you get it working I would love to check it out and see if it's something that should be part of simpleWeather.

**Comment by isaachinman** [comment]
Fair enough. Not even sure if I'll use simpleWeather, but it's a great plugin. I'm trying to create a landing page for a website that allows access if it's dark outside and doesn't if it's daytime.

**Comment by isaachinman** [comment]
var weatherUrl = 'https://query.yahooapis.com/v1/public/yql?format=json&rnd='+now.getFullYear()+now.getMonth()+now.getDay()+now.getHours()+'&diagnostics=true&callback=?&q=';


Do you know if there is a way of having getHours return a 24hr time from the Yahoo API?

**Comment by fleeting** [comment]
`getHours()` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getHours) in that line returns an integer between 0 and 23 already. However, that is the the hour it is right now for the client. It doesn't have anything to do with Yahoo or the API call besides avoiding a cached result. As far as I know the Yahoo API only returns 12 hour format.

**Comment by isaachinman** [comment]
Yes I know. And yup, according to this page, it only returns 12hr:

http://api-portal.anypoint.mulesoft.com/yahoo/api/yahoo-weather-api/docs/reference

Thanks anyways!

**Comment by isaachinman** [comment]
Just as a heads up, I solved the issue by using this function:

/* CONVERT 12HR TO 24HR */
function ConvertTime(t){
   // Get your time (using a hard-coded year for parsing purposes)
   var time = new Date("0001-01-01 " + t);
  
   // Output your formatted version (using your DateTime)
   var formatted = time.getHours() + ':' + ('0' + time.getMinutes()).slice(-2);
  
   // Return your formatted time
   return formatted;
}
/* END CONVERT 12HR TO 24HR */

And then just calling stuff like:

html = '<p>Sunrise:&nbsp;'+ConvertTime(weather.sunrise)+'</p>';
