### ISSUE TITLE
Geolocation not working

### ISSUE THREAD

**Issue by icommstudios** [monkeecreate/jquery.simpleWeather#125]
Hello, first off great little plugin, thanks for developing it! - I am having trouble getting the geolocation to work.  Here's the test link: http://198.20.249.142/~caboodle/ - Hover over the weather in the top right corner and a box slides up - This box contains "Use Your Location" button but it is hidden as if geolocation is not supported BUT your example works.

Any ideas?  Thanks in advance.

**Comment by icommstudios** [comment]
Any help is greatly appreciated!  Thanks

**Comment by fleeting** [comment]
Honestly I'm not entirely sure. I took a quick look but the code you are using works in the demos and on other sites so it looks to be something on your setup. It seems this code isn't running -
```
if ("geolocation" in navigator) {
  jQuery('.js-geolocation').show(); 
} else {
  jQuery('.js-geolocation').hide();
}
```

Again that same part works in the codepen demo though.

**Comment by icommstudios** [comment]
I completely understand that but nothing jumps out at you?  I need this for a project I am working on so I'd be willing to pay for your time if you're confident you could fix it. 

Be Happy,

Travis Hedrick
(sent from my mobile office)

**Comment by rumblestrut** [comment]
Hi Travis,

Using Chrome's Developer Tools, I notice that you're getting some 304 errors: http://www.checkupdown.com/status/E304.html. Just wondering if that has anything to do with it (I am unsure)?

**Comment by samuelfine** [comment]
@icommstudios As @fleeting mentioned, it appears that the code in your `custom.js` file—which functions correctly—isn't being fired for some reason. I'd start by adding some `console.log()`s inside that file to see when/if the code is being executed, and see what sort of values are being returned.

(If you're still looking for a fix, shoot me an email. hi at my username dot com. :)
