### ISSUE TITLE
Cache option?

### ISSUE THREAD

**Issue by ckubs** [monkeecreate/jquery.simpleWeather#126]
I want to use this jquery plugin with my wordpress, and I want to know if it has any sort of caching mechanism.

Or, how hard will it be for a normal user( not developer) to implement such an option, to see if I can handle it. :)
Thank you.

**Comment by fleeting** [comment]
Currently there is no caching. I don't imagine it would be that hard to store the data (all or just what you need) and then use that cache instead.

**Comment by adrianmihalko** [comment]
Could you please write a quick localStorage example for x hour caching?

**Comment by fleeting** [comment]
I have it on my list of demos to do with the next release of simpleWeather but it's doubtful it will be anytime soon. That said, any decent localStorage tutorial found from a Google search should get you what you need, just simply replacing the data saved and called with simpleWeather data.

**Comment by adrianmihalko** [comment]
I am trying to make cahing on the server, not on the user side. So I am trying to cache the URL which we retrieve from Yahoo:

https://query.yahooapis.com/v1/public/yql?format=json&rnd=20159219&diagnostics=true&callback=?&q=select * from weather.forecast where woeid in (select woeid from geo.placefinder where text="Parkany" and gflags="R" limit 1) and u="c"

This is what SimpleWeather query from Yahoo. It would be easy to cache the returned json on the server, but I get error:

**/yql_invalid_callback({"error":{"lang":"en-US","diagnostics":null,"description":"Invalid JSON callback parameter yql_invalid_callback"}});

Of course I am decoding the URL before I test.

**Comment by adrianmihalko** [comment]
I just removed "callback=?" and it's working now, but why it's working from your code and why the raw URL version not?
