### ISSUE TITLE
Issues with weather.link property

### ISSUE THREAD

**Issue by dvdghazaryan** [monkeecreate/jquery.simpleWeather#128]
Hello!

At first thanks for such a great plugin! I am having problems with weather.link property it is opening the default yahoo weather page with my local position forecast information. I would assume it should bring forecast information for the location for witch the plugin is setup (instead of my local one) . The "Full Forecast at Yahoo! Weather" link in "Data Dump" example page (http://codepen.io/fleeting/pen/yjhBK/) also redirects to my local location, instead of Austin, TX for which it is setup. Can you suggest if that is broken or am i doing something wrong?

Thanks in advance!

**Comment by fleeting** [comment]
Yeah, it seems to have been broken for awhile on Yahoo's end. Ever since they rolled out their new weather.yahoo.com stuff all those links just redirect back to their main weather page and attempts to detect your location instead. I'm not sure of a work around.

**Comment by dvdghazaryan** [comment]
ok, thanks much for quick feedback!
