### ISSUE TITLE
API returning 'UNKNOWN'

### ISSUE THREAD

**Issue by mattaxell** [monkeecreate/jquery.simpleWeather#129]
Apologies as I appreciate this isn't an issue with the plugin itself but I'm attempting to use it on a tourism website for Littlehampton, a town situated on the south coast of England. Yahoo has returned the current weather condition as 'UNKNOWN' solidly for the past 3 weeks.

I just wondered if anyone had any previous experience of this and if there were any steps to make Yahoo aware / implement a fix?

(It's also currently returning unknown for the majority of towns/cities close by including Portsmouth and Brighton)

**Comment by stakach** [comment]
I'm also seeing a similar issue with surrounding suburbs of Sydney.
The fix could be to use the first of the forecast data if `condition.code == "3200"`

Here is a sample of the response I'm receiving:

```json
{
  "title": "Conditions for Orchard Hills, AU at 8:59 pm AEST",
  "lat": "-33.81",
  "long": "150.73",
  "link": "http://us.rd.yahoo.com/dailynews/rss/weather/Orchard_Hills__AU/*http://weather.yahoo.com/forecast/ASXX0088_c.html",
  "pubDate": "Mon, 28 Sep 2015 8:59 pm AEST",
  "condition": {
    "code": "3200",
    "date": "Mon, 28 Sep 2015 8:59 pm AEST",
    "temp": "15",
    "text": "Unknown"
  },
  "description": "\n<img src=\"http://l.yimg.com/a/i/us/we/52/3200.gif\"/><br />\n<b>Current Conditions:</b><br />\nUnknown, 15 C<BR />\n<BR /><b>Forecast:</b><BR />\nMon - Partly Cloudy. High: 23 Low: 9<br />\nTue - Mostly Sunny. High: 27 Low: 11<br />\nWed - PM Showers. High: 24 Low: 14<br />\nThu - Partly Cloudy. High: 29 Low: 13<br />\nFri - Mostly Sunny. High: 27 Low: 11<br />\n<br />\n<a href=\"http://us.rd.yahoo.com/dailynews/rss/weather/Orchard_Hills__AU/*http://weather.yahoo.com/forecast/ASXX0088_c.html\">Full Forecast at Yahoo! Weather</a><BR/><BR/>\n(provided by <a href=\"http://www.weather.com\" >The Weather Channel</a>)<br/>\n",
  "forecast": [
    {
      "code": "29",
      "date": "28 Sep 2015",
      "day": "Mon",
      "high": "23",
      "low": "9",
      "text": "Partly Cloudy"
    },
    {
      "code": "34",
      "date": "29 Sep 2015",
      "day": "Tue",
      "high": "27",
      "low": "11",
      "text": "Mostly Sunny"
    },
    {
      "code": "39",
      "date": "30 Sep 2015",
      "day": "Wed",
      "high": "24",
      "low": "14",
      "text": "PM Showers"
    },
    {
      "code": "30",
      "date": "1 Oct 2015",
      "day": "Thu",
      "high": "29",
      "low": "13",
      "text": "Partly Cloudy"
    },
    {
      "code": "34",
      "date": "2 Oct 2015",
      "day": "Fri",
      "high": "27",
      "low": "11",
      "text": "Mostly Sunny"
    }
  ],
  "guid": {
    "isPermaLink": "false",
    "content": "ASXX0088_2015_10_02_7_00_AEST"
  }
}
```

**Comment by fleeting** [comment]
That's actually a great idea, just using todays forecast code and text if current code is 3200. I may see about handling that inside simpleWeather where if current is 3200/Unknown, it will automatically pass back `forecast[0]` instead.

**Comment by stakach** [comment]
Sweet! It means a little less logic on the app side (as I check for that condition manually now) and it's a whole lot less surprising - my code is based of your geolocation example, it was basically a copy paste job until I hit that 3200 code.

Can't complain though, awesome library, thanks for sharing!

**Comment by fleeting** [comment]
Thanks for the comments! Yeah, I think something like this can be handled within simpleWeather. I'll release a fix for this version later this week but I also have a complete rewrite of the script coming out before long.
