### ISSUE TITLE
Precipitation

### ISSUE THREAD

**Issue by tmurren** [monkeecreate/jquery.simpleWeather#130]
Is there a way to display percent chance of precipitation using simpleWeather? Ideally it could list the precipitation prediction hourly for the future (not just the current precipitation).

**Comment by tmurren** [comment]
I see that simpleWeather uses Yahoo weather to grab it's information, and Yahoo weather seems to use the Weather Channel API (I think) which has the ability to view precipitation.

**Comment by fleeting** [comment]
As far as I know the Yahoo Weather API doesn't give the chance of precipitation. You can see what is returned at https://developer.yahoo.com/weather/.
