### ISSUE TITLE
API returning [OBJECT OBJECT]

### ISSUE THREAD

**Issue by chrokoth** [monkeecreate/jquery.simpleWeather#131]
I am doing a website for a hotel in Kisumu, Kenya. The API was working fine except today it's just displaying [OBJECT OBJECT] instead of the actual weather. I changed the location codes and it works.  Is there a possibility the area has a weather code that hasn't been defined?

**Comment by fleeting** [comment]
I have a pending fix I need to push out this week. All the codes should be defined, typically this happens when the API errors out or doesn't return any reported weather for a location and I'm not catching it correctly. I'll work on an update to see about fixing the issue.

**Comment by bamlhs** [comment]
Hello,
the error [OBJECT OBJECT] city not found. did you push the fix?
 
tnx

**Comment by gustavorojas** [comment]
I have the same problem!!! Do you have solution???

**Comment by fleeting** [comment]
This should be fixed in `v3.1.0`.
