### ISSUE TITLE
Return today and tomorrow?

### ISSUE THREAD

**Issue by aaronhb** [monkeecreate/jquery.simpleWeather#133]
Is there a way to have it return today and tomorrow or set how many days the forecast returns?

**Comment by fleeting** [comment]
It already provides a five day forecast so you can use any of those days you want, no way to request more though. http://codepen.io/fleeting/pen/skbqf

**Comment by aaronhb** [comment]
Yeah but how would i only display today and tomorrow?

**Comment by aaronhb** [comment]
Thanks for the quick reply by the way! AWESOME!

**Comment by aaronhb** [comment]
I tried using this but gives me an error of one is undefined. 

<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.simpleWeather/3.0.2/jquery.simpleWeather.min.js"></script>
    <script>
	$(document).ready(function() {
		$.simpleWeather({
		location: '77042',
		woeid: '',
		unit: 'f',
		success: function(weather) {
		  html = '<ul>';
			html += '<li class="forecast-day">'+weather.forecasts.one.day+' <i class="sw-icon sw-icon-'+weather.forecasts.one.code+'"></i> '+weather.forecasts.one.high+' '+weather.forecasts.one.low+' '+weather.forecasts.one.forecast+'</li>';
			html += '<li class="forecast-day">'+weather.forecasts.two.day+' <i class="sw-icon sw-icon-'+weather.forecasts.two.code+'"></i> '+weather.forecasts.two.high+' '+weather.forecasts.two.low+' '+weather.forecasts.two.forecast+'</li>';
		  html += '</ul>';
		  $("#weather").html(html);
		},
		error: function(error) {
			$("#weather").html('<p>'+error+'</p>');
		}
		});
	});
	</script>

**Comment by fleeting** [comment]
I would check out the documentation table of data on simpleweatherjs.com. There is no `weather.forecasts.one.day` instead it is `weather.forecast[0].day`. `forecast[0]` is today with `forecast[1]` being tomorrow and so on through `forecast[4]` giving you a five day forecast.
