### ISSUE TITLE
How do I instal SimpleWeather.js?

### ISSUE THREAD

**Issue by propergent** [monkeecreate/jquery.simpleWeather#134]
Hello, this should be simple enough. Im just looking to do a very basic implementation by starting with the demo files, but the end goal is to create something very simple (as in this Basic example http://codepen.io/fleeting/pen/xwpar).  I have my script files linking (and the other files are working) but they don't seem to be returning any results nor appear to be linking. 

The browser is telling me that the jquery is not defined, but again appears to be linked correctly. Any help would be awesome! Love this app, just want to know how to use it!

![screen shot 2015-05-27 at 10 09 39 am](https://cloud.githubusercontent.com/assets/12628712/7839554/8f48d460-0458-11e5-8ce7-d084fef7aa8f.png)

**Comment by fleeting** [comment]
It looks like you are missing jQuery. You will need to include it as well, might want to check out http://jquery.com. jQuery should be included above the simpleWeather include. Also, it looks like you are including simpleWeather.js and simpleWeather.min.js when you only need one. I would recommend only using simpleWeather.min.js instead.

**Comment by propergent** [comment]
Thanks for getting back. I do have jQuery linked right now, please see version 1.10.2.min and screenshot below. Please let me know if I need another version or if you have any other advice.

**Comment by fleeting** [comment]
Now it looks like you have jQuery included twice. One with `js/vendor/jquery.js/` and another with `http://code.jquery.com/jquery-1.10.2.min.js`. You can remove the second one (code.jquery.com for now). However, in this case it looks like simpleWeather is being included at the top of the file. You must include simpleWeather after jQuery, so you need to move it down below jQuery like the other scripts are. As you have simpleWeather at the top, it is trying to run it before it loads jQuery which is causing the error.

**Comment by propergent** [comment]
Ok, no errors now. Im using the Foundation framework and am trying to place the weather div within a row. The CSS is linked in and is producing a blue background, but none of the data from the js is pulling in. Thanks again for your help. 

![screen shot 2015-05-27 at 11 05 23 am](https://cloud.githubusercontent.com/assets/12628712/7841150/51a50284-0460-11e5-8c10-5d65765fce97.png)

**Comment by fleeting** [comment]
I would need to see your init of simpleWeather. I saw you including the simpleWeather script but haven't seen where you are actually calling it. I would check out the demos on http://simpleweatherjs.com for some examples.

**Comment by propergent** [comment]
I started by just pluggin in the demo files(right now I just have jquery.simpleWeather.min.js, the div, and the jquery set) and haven't changed them, just using them as they are. I am aiming to create something as simple as the Bare Minimum example. Even when I swap out the JS from the bare minimum example into jquery.simpleWeather.min.js, I am still just getting a large CSS background. 

Apologies if im missing something really easy. Thanks for your help

**Comment by fleeting** [comment]
No, you shouldn't modify simpleWeather.min.js at all. That is the script itself. However, the init code from the demo you will need to include in your site below the simpleWeather.min.js include. I mean the demos work as expected so this is just missing that code on your end.

**Comment by propergent** [comment]
Duh! Got it! Thanks a ton for your help! You rock. Good luck with the rain
