### ISSUE TITLE
Weather link redirects to Yahoo weather home and not forecast details

### ISSUE THREAD

**Issue by terracatta** [monkeecreate/jquery.simpleWeather#135]
I am attempting to pull weather for various locations in france (Currently Saint-Content, France). The API is generating the following URL for more details "http://us.rd.yahoo.com/dailynews/rss/weather/Saint-Contest__FR/*http://weather.yahoo.com/forecast/FRBN1113_f.html". 

When I visit this URL in my browser I am simply redirected to the Yahoo weather home page and I do not get more forecast details.

**Comment by fleeting** [comment]
Yeah, unfortunately it has been that way for awhile. Yahoo made several changes to the weather API awhile back and launched a new weather website that seemed to break that forecast link they provide. It's not something in my control and I've contact Yahoo support about it before with no response. I need to make note of that in the documentation.
