### ISSUE TITLE
Wordpress Integration

### ISSUE THREAD

**Issue by IvoDanic** [monkeecreate/jquery.simpleWeather#136]
How can i integrate this plugin on a simple html for wordpress? there is a plugin for wordpress?  Thanks for all by the way!

**Comment by fleeting** [comment]
simpleWeather is just a jQuery plugin so it doesn't need anything special besides jQuery to be included. Take a look at the demos and should just be able to include simpleWeather and then init the script within your WordPress templates. No need for a WordPress plugin.
