### ISSUE TITLE
Change number of weather.code

### ISSUE THREAD

**Issue by corentin-branquet** [monkeecreate/jquery.simpleWeather#138]
I noticed that 'weather.code' begin at 0 to 47. 
When I change icons, I want 'weather.code' begin at 0 to 28. 
How can I change that ?

**Comment by fleeting** [comment]
This isn't possible, those are the codes Yahoo returns for the weather condition. See https://developer.yahoo.com/weather/documentation.html#codes for details. If you are trying to use custom icons or a font, you just need to match up the weather code returned with whatever your icon is using. Check out the demo http://codepen.io/fleeting/pen/xklfq?editors=010 and line 51+ of the CSS. I'm matching each weather code from 0 to 47 with the letter for the font icon that I want to show up.
