### ISSUE TITLE
Add translations or a way to translate forecast condition to other languages

### ISSUE THREAD

**Issue by fmdiaz** [monkeecreate/jquery.simpleWeather#14]
Maybe in external files that could be called from the main file, replacing the default values from yahoo weather. I have a list of the terms translated to spanish if useful for testing.

**Comment by adrianmihalko** [comment]
Hungarian translate:

var codes = new Array();

codes[0] = "Tornádó"; //"tornado"
codes[1] = "Trópusi vihar"; //"tropical storm"
codes[2] = "Hurrikán"; //"hurricane"
codes[3] = "Súlyos zivatarok"; //"severe thunderstorms"
codes[4] = "Zivatarok"; //"thunderstorms"
codes[5] = "Vegyes eső és hó"; //"mixed rain and snow"
codes[6] = "Vegyes eső és ónos hó"; //"mixed rain and sleet"
codes[7] = "Vegyes hó és ónos eső"; //"mixed snow and sleet"
codes[8] = "Ónos szitálás"; //"freezing drizzle"
codes[9] = "Szitálás"; //"drizzle"
codes[10] = "Ónos eső"; //"freezing rain"
codes[11] = "Záporok"; //"showers"
codes[12] = "Záporok"; //"showers"
codes[13] = "Hózáporok"; //"snow flurries"
codes[14] = "Könnyű hózáporok"; //"light snow showers"
codes[15] = "Hófúvás"; // "blowing snow"
codes[16] = "Hó"; //"snow"
codes[17] = "Jégeső"; //"hail"
codes[18] = "Ónos eső"; //"sleet"
codes[19] = "Por"; //"dust"
codes[20] = "Ködös"; //"foggy"
codes[21] = "Homály"; //"haze"
codes[22] = "Füstös"; //"smoky"
codes[23] = "Lármás"; //"blustery"
codes[24] = "Szeles"; //"windy"
codes[25] = "Hideg"; //"cold"
codes[26] = "Felhős"; //"cloudy"
codes[27] = "Többnyire felhős (éjszaka)"; //"mostly cloudy (night)"
codes[28] = "Többnyire felhős (nappal)"; //"mostly cloudy (day)"
codes[29] = "Részben felhős (éjszaka)"; //"partly cloudy (night)"
codes[30] = "Részben felhős (nappal)"; //"partly cloudy (day)"
codes[31] = "Tiszta égbolt (éjszaka)"; //"clear (night)"
codes[32] = "Napos"; //"sunny"
codes[33] = "Szép idő (éjszaka)"; //"fair (night)"
codes[34] = "Szép idő (nappal)"; //"fair (day)"
codes[35] = "Eső és jégeső"; //"mixed rain and hail"
codes[36] = "Forróság"; //"hot"
codes[37] = "Elszigetelt zivatarok"; //"isolated thunderstorms"
codes[38] = "Elszórtan zivatarok"; //"scattered thunderstorms"
codes[39] = "Elszórtan zivatarok"; //"scattered thunderstorms"
codes[40] = "Elszórtan záporok"; //"scattered showers"
codes[41] = "Erős havazás"; //"heavy snow"
codes[42] = "Elszórtan hózápor"; //"scattered snow showers"
codes[43] = "Erős havazás"; //"heavy snow"
codes[44] = "Részben felhős"; //"partly cloudy"
codes[45] = "Viharok"; //"thundershowers"
codes[46] = "Hózáporok"; //"snow showers"
codes[47] = "Elszigetelt viharok"; //"isolated thundershowers"
codes[3200] = "Nem elérhető"; //"not available"

$.simpleWeather({
    woeid: '784565',
    unit: 'c',
    success: function(weather) {

        html = '<h2>'+weather.city+', '+weather.region+'</h2>';
        html += '<img style="float:left;" width="125px" src="'+weather.image+'">';
        html += '<p>'+weather.temp+'&deg; '+weather.units.temp+'<br /><span>'+codes[weather.code]+'</span></p>';
        html += '<a href="'+weather.link+'">Zur Vorhersage &raquo;</a>';
        html += '<p><span>Morgen '+codes[weather.tomorrow.code]+' bei '+weather.tomorrow.low+' bis '+weather.tomorrow.high+'&deg; '+weather.units.temp+'</span></p>';
        $("#weather").html(html);
    },
    error: function(error) {
        $("#weather").html('<p>'+error+'</p>');
    }
});
