### ISSUE TITLE
Translate to Portuguese

### ISSUE THREAD

**Issue by webpac** [monkeecreate/jquery.simpleWeather#140]
Translate 'weather.currently' to portuguese

add a variable:
var textMapping = {"Partly Cloud":"Parc. Nublado","Showers":"Chuva","Partly Cloudy":"Parc. Nublado","AM Showers":"Chuva de manhã","PM Showers":"Chuva à noite","PM Thunderstorms":"Temporal à noite","Scattered Thunderstorms":"Trovoadas dispersas","Light Rain with Thunder":"Chuva fina com trovão","Thunderstorms":"Temporal","Heavy Rain":"Chuva persistente","Mostly Sunny":"Parc. ensolarado","Light Rain":"Chuva fina","Fog":"Neblina","Fair":"Tempo bom","Sunny":"Ensolarado","AM Rain":"Chuva de manhã","PM Rain":"Chuva à noite","Mostly Cloudy":"Prev. Nublado","Isolated Thunderstorms":"Temporal isolado","Thundershowers":"Temporal","Heavy Thunderstorms":"Temporal forte","Clear":"Tempo bom","Rain":"Chuva","Cloudy":"Nublado"}

change line 50
weather.currently = result.item.condition.text;
+
weather.currently = textMapping[result.item.condition.text]

**Comment by ALYSSONBSB** [comment]
Pacheco, 
Thanks, but does not work for:
Obrigado pela contribuição, Porém não funciona para o:


weather.text = result.item.forecast[0].text;
(weather.text = textMapping[result.item.forecast[0].text];)

**Comment by fleeting** [comment]
For now simpleWeather isn't going to include translations, it's up to each person to do their own. I do plan to have a section on the website to link to these type of translations for those who need it in the future.
