### ISSUE TITLE
The you might not need jQuery version.

### ISSUE THREAD

**Issue by fleeting** [monkeecreate/jquery.simpleWeather#141]
Pushing towards v4.0.0 which will drop the jQuery dependency and have a vanilla JavaScript version. I'm not sure if the jQuery plugin will remain in v4 or if I will just link back to v3 for those that still want it. I'll most likely continue to support the jQuery plugin until I don't.
- [x] Remove $.getJSON() in favor of XMLHttpRequest and JSON.parse.
- [x] Utilize data-attributes to insert weather data. Ex: <span data-weather="temp"><span>
- [ ] Need to do a better job of catching and handling errors.
- [ ] Browser test across Chrome, Firefox, Safari, and IE10+.
- [ ] Update the primary demos and leave a note in the others about version.
- [ ] Update docs for new version. Also, we should document browser support better.
- [ ] Should we hold the release until the website redesign is complete? Leaning towards no as I don't have a timeline for it with it in the design phase now.
- [ ] Transfer this repo from `monkeeCreate` to my personal account. Then create a placeholder repo here to direct people to it's new home.
- [ ] Release v4.0.0 to the world.

**Comment by rhkiyani** [comment]
Suggestions for version 4.0
- Extend forecast from 4 days to 10
- Hourly forcast temp

**Comment by fleeting** [comment]
@rhkiyani Unfortunately the current Yahoo Weather API doesn't contain data for hourly forecast and only provides a five day forecast (today + next four days) so simpleWeather is currently limited by that. I'm constantly looking at other weather feeds but so far I'm sticking with the Yahoo API.

**Comment by MahmoudAlaaOmran** [comment]
Hello, when I use the plugin or yahoo weather api , it returns different values and different days for the current day with each refresh/request, do you have any idea about it ?

**Comment by fleeting** [comment]
@MahmoudAlaaOmran See issue #156, it's a known Yahoo issue and nothing I can do. Sorry.

**Comment by eighthday** [comment]
yes! really looking forward to no jquery.

**Comment by eighthday** [comment]
oh, sorry just seen this is a year old.

**Comment by fleeting** [comment]
@eighthday ha, it's still coming. In fact it's basically done but I didn't release it back when Yahoo's API was down for several days. Things have been good since so I still plan to get this out very soon.

**Comment by eighthday** [comment]
ok great, thanks for the update.
