### ISSUE TITLE
SimpleWeather Enter Location

### ISSUE THREAD

**Issue by larsenv** [monkeecreate/jquery.simpleWeather#143]
Hi.

I was wondering if it's possible to enter your current location with SimpleWeather instead of using the GeoLocation thing?

If so... how can I do so?

Thanks.

**Comment by fleeting** [comment]
Sure! Instead of detecting just need to ask the user for a location, pass that to simpleWeather and wait for the data to be returned. Might provide some tips on a user correctly formatting a location or Yahoo may not find it correctly.
