### ISSUE TITLE
Is there a way to also add the location Time?

### ISSUE THREAD

**Issue by Goldendust20** [monkeecreate/jquery.simpleWeather#147]
Hello -
First and foremost, EXCELLENT plugin.  I'm currently using the "multiple locations" code for a project, but the person I'm building this for has asked for the time to also be represented for each location.

Is this possible?  If yes, could you please tell me how I would go about surfacing this?

Thank you!!
B. Golden

**Comment by fleeting** [comment]
`weather.updated` holds the date time stamp of when the weather data was last updated. It's formatted already but you can change it by using moment.js. I have a quick demo of it at http://codepen.io/fleeting/pen/BExry.
