### ISSUE TITLE
Please include a icon service.

### ISSUE THREAD

**Issue by ahayder** [monkeecreate/jquery.simpleWeather#149]
That's all nothing more. By the way the api is very easy to use and a good one.

**Comment by fleeting** [comment]
I'm not really sure what is being requested here. simpleWeather doesn't have any icons besides the ones Yahoo returns in the API. You are free to use your own but it's unlikely I'll bundle custom icons with simpleWeather.

**Comment by ahayder** [comment]
We are always free to use anything. But if I have to use custom icon in simpleWeather than what's the point of this nice & easy api. Using custom icon is really a pain. I used open weather api only for the icon, along side of simple weather in a project.

**Comment by fleeting** [comment]
Yahoo includes icons for every weather condition and simpleWeather includes support for those. It's in the variable `weather.image` or `weather.thumbnail`. You can use them in an image source like `<img src="'+weather.image+'">`. You can see what [sunny](https://s.yimg.com/zz/combo?a/i/us/nws/weather/gr/32d.png) looks like as an example. So, there are icons available for use without having to use custom ones. You are free to use the included Yahoo ones or custom ones.
