### ISSUE TITLE
Weather icons

### ISSUE THREAD

**Issue by theberengersniper** [monkeecreate/jquery.simpleWeather#150]
Hi James, please accept my apologies for creating an issue when I guess that's not really what this is, I just don't have Twitter so couldn't contact you any other way.

I've created my own custom icon set, numbered as per the Yahoo condition codes, and wondered if you were interested in linking to them via your site. I know you already point people at icon sets but so far as I can tell mine would be the only one that's complete, insofar as Yahoo's codes are concerned at least. I have a white versions and the same set coloured.

If you're interested let me know and I'll provide a URL. In any case, thank you very much for an awesome plugin.

**Comment by fleeting** [comment]
Thanks for checking out simpleWeather! I would love to check out the icons and possibly link to them. Let me know the url.

**Comment by theberengersniper** [comment]
Hi James,

Here's a tinyURL to a zip file containing coloured and white icons, plus a preview image of the coloured set: http://tinyurl.com/p4shbyr

Fraser.

**Comment by fleeting** [comment]
Thanks for this. However, I'm not comfortable just linking to a third party zip file. Ideally if you could put a post up about them, showing the preview image (even a github repo of them), I could link to it vs directly to a download. Once you get them up somewhere let me know the new url.

Also, a quick suggestion would be to also make these into an icon font as well as the png files. This way people could use either (I prefer icon fonts personally). [IcoMoon](https://icomoon.io/app/) has a great app to generate fonts from uploading icons if needed.

**Comment by theberengersniper** [comment]
Hi James, apologies for sending a link directly to a zip, that was a bit of a school boy error. I have now created a repository and committed them all to that: https://github.com/theberengersniper/weather-icons

I plan to update the sets over the next few weeks by adding additional sizes and, as you suggested, an icon font version.

**Comment by fleeting** [comment]
Awesome, I'll get a link added to it soon. We are currently working on a redesign of the site to better organize extra data like this so it might be a little bit. I'll reopen this ticket as a reminder. Thanks again.
