### ISSUE TITLE
weather.currently return types

### ISSUE THREAD

**Issue by trdwll** [monkeecreate/jquery.simpleWeather#152]
Could you give me a full list of return types for <strong>weather.currently</strong>?
I'm building something that requires a list.

Thanks

**Comment by fleeting** [comment]
I'm honestly not entirely sure the list of phrases `currently` provides. I know for the most part they match up with the condition codes found at https://developer.yahoo.com/weather/documentation.html#codes.

**Comment by trdwll** [comment]
Yeah, I saw that right after I wrote this. Thanks anyways. :)
