### ISSUE TITLE
Icon is replaced with a number

### ISSUE THREAD

**Issue by alexi721** [monkeecreate/jquery.simpleWeather#153]
James:
Thank you for very much for your very useful weather plugin.

We are using the plugin for our Intranet website here at SFO and noticed that starting today the icon doesn't get displayed. Instead we are seeing a number displayed.
![weatherjs_number_instead_icon_displayed](https://cloud.githubusercontent.com/assets/115497/10797688/10190048-7d61-11e5-91a3-7cb8b5444c9c.jpg)

Any ideas what is causing this and how to fix it.

BTW, I see the same behaviour on your site at:
http://simpleweatherjs.com

Thank you in advance for your response, Alex

**Comment by fleeting** [comment]
My guess is you are hot linking the icon font I use in the demo and that link was down at some point. To avoid this, it's highly recommended not hot linking the font and instead download it from http://fonts.artill.de/collection/artill-weather-icons and upload it to your server and use from there. If I ever change the demos, remove the font, or anything like that it would break for anybody that opted to hot link vs download. Thanks!
