### ISSUE TITLE
Randomly displaying temperature between lowest and highest weather for the day

### ISSUE THREAD

**Issue by RUIFERNANDE5** [monkeecreate/jquery.simpleWeather#154]
Hello,
Thank you very much for such nice plugin.
However I seem to be randomly getting temperatures from 11ºC (today's minimum temperature) to 21º (today's highest temperature) on page reload.

Heres my code:

```
loadWeather('40.278242,-8.281115','');

function loadWeather(location, woeid) {
    $.simpleWeather({
        location: location,
        woeid: woeid,
        unit: 'c',
        success: function(weather) {
            if(weather.code=='3200') iconCode = weather.todayCode;
            else iconCode = weather.code;

            html = '<ul><li><i class="icon-'+iconCode+'"></i>'+weather.city+',';
            html += '<h2>'+weather.temp+'&deg;'+weather.units.temp+'</h2>';
            $("#weather").html(html);
        },
        error: function(error) {
            $("#weather").html('');
        }
    });
}
```

Did not found any post with that issue so..
Do you have a fix or any idea why is it happening?

Thanks in advance.

**Comment by fleeting** [comment]
It looks like Yahoo isn't returning a consistent temp over the API for that location. It's actually returning the code `3200` which is unknown weather condition, so it could be they just don't have data for that location through the API. It is something with Yahoo's data though. Here is the [direct feed](https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Penacova%2C%20Portugal%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys) and as you refresh the current temp does change. You can see the same in their [yql console](https://developer.yahoo.com/yql/console/?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Penacova%2C%20Portugal%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys) for debugging.

**Comment by RUIFERNANDE5** [comment]
That was my first thought. However it's weird that the temp is jumping between the min and the max.
Thanks anyway
