### ISSUE TITLE
weather widget returns incorrect data

### ISSUE THREAD

**Issue by vjcode** [monkeecreate/jquery.simpleWeather#155]
When doing a "refresh" of the page it comes back with different values, and times as well.
For example click on the data-dump demo http://codepen.io/fleeting/pen/yjhBK/
and hit refresh(F5 or Ctrl-R), and you will see different values: for instance when I did it, I get various values - first 2 lines shown below, tested with Chrome46 and IE11:

weather.title: Conditions for Austin, TX at 10:50 pm CST
weather.temp: 61

weather.title: Conditions for Austin, TX at 7:50 am CST
weather.temp: 59

weather.title: Conditions for Austin, TX at 8:49 am CST
weather.temp: 60

weather.title: Conditions for Austin, TX at 12:49 am CST
weather.temp: 71

**Comment by ethan1341** [comment]
I am having the same problem everytime I refresh it says last updated of a date from a couple days ago.

**Comment by fleeting** [comment]
I've been having the same issue but it seems to be on Yahoo's end. If you view the [feed directly](https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22boston%2C%20ma%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys) and refresh you see the last updated value change back and forth. The same goes if you just refresh the [Yahoo API example](https://developer.yahoo.com/weather/) a few times the values change. Unfortunately there isn't anything I can do on my side as that's the data Yahoo is returning.

**Comment by fleeting** [comment]
That said, I'm constantly looking at other data sources to switch to. Originally Yahoo's API was lightweight, fast, and easy to lookup locations. However, they have been having lots of quirks like this coming up over the past few months so I may have to look harder at a replacement API.

**Comment by ethan1341** [comment]
Could I just make a function. That if the updated isn't equal to now ( the current date ) get the date again?

**Comment by vjcode** [comment]
Yes, that's exactly what I did and was going to update my post. I'm trying to figure out where to complain. Their support page returns a 404. I sent them a tweet. Let's see. Without accurate source data, this app is dead in the water :( The NOAA api may be an alternative - you'll have to parse XML though... Anyway, thanks
