### ISSUE TITLE
Radom data at every update

### ISSUE THREAD

**Issue by vushe** [monkeecreate/jquery.simpleWeather#156]
Hello! 
And thanks for the nice piece of code!

I am confused, however, on how it works even with standard example
http://codepen.io/fleeting/pen/skbqf

Each time I refresh page, I see random current weather and random days in forecast... In my own code I see also random update time (city is Helsinki)...

**Comment by Gloompirate** [comment]
I am also seeing this issue, sometimes when the page loads the correct data is there, but if you reload the page you will see information from a previous date, and every time the page is refreshed a different date from the past week is displayed.

**Comment by augustudios** [comment]
I was having the same issue also. I changed the "town, state" to the actual WOEID identifier number and it seems to be refreshing properly each time. Not sure why the difference, but I'll take it. :)

**Comment by vushe** [comment]
Good that you manage to solve this problem, but unfortunately WOEID doesn't help in my case.

**Comment by Gloompirate** [comment]
I am only using the WOEID, and always have been, but it seems that from Friday of last week it has stopped working properly and now just gives me data for a random day in the past week instead of today. I haven't changed anything in the setup and it was previously working for the past few months.

**Comment by richbradshaw** [comment]
I'm using location search, and the same is happening - random weather each time.

**Comment by Tiliavir** [comment]
I am only using the location parameter and have the same issue. Looking at the "update" result, yahoo seems to return outdated information ...

**Comment by BobStevens** [comment]
The random/stale data can also be seen on Yahoo Developer Networks "Sample Weather API Response" page, https://developer.yahoo.com/weather/ 
Repeatedly test the same YQL query and it will return conditions from a random day in the past week or more.

**Comment by propergent** [comment]
Anyone else lose the icons as well? I seem to be getting a random/stale set of data (using WOEID) as and random character in place of the weather icons themselves.

![screen shot 2015-11-17 at 3 25 51 pm](https://cloud.githubusercontent.com/assets/12628712/11225408/92850eee-8d3f-11e5-92f6-f7f4b6e316cd.png)

**Comment by vushe** [comment]
I am using AJAX and update weather in background. So, my temporary fix was to increase frequency of the background updates and to reject wrong updates as follows (rough, but I hope there will be a fix in plugin soon):

var firstday_date = weather.forecast[0].date.split(" ");
if (now.getDate() == parseInt(firstday_date[0])) {
		   $("#weather").html(html);
};

This will not help if you just reload page, something like while(now.getDate() != parseInt(firstday_date[0])) {...} might be implemented?

Then I noticed that weather icons are wrong. I fixed it like that (seems to be working, but I am not 100% sure)
html += '<i class="icon-'+(weather.code-1)+'"></i> ';

**Comment by Gloompirate** [comment]
I have done a similar thing to vushe above, check the date being returned in the forecast, if it is correct display the data, if not request the data again, this so far is working.

**Comment by rhkiyani** [comment]
I am experiencing same issue. The weather data is different on each hard refresh or background refresh.

**Comment by fleeting** [comment]
Yahoo seems to be having problems with their weather feed and no clue if/when they plan to fix it. If you view the [feed directly](https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22boston%2C%20ma%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys) and refresh you see the data changes each time. The same goes if you just refresh the [Yahoo API example](https://developer.yahoo.com/weather/) a few times the values change. Unfortunately there isn't anything I can do on my side as that's the data Yahoo is returning. A few people have tried to contact Yahoo support over the past week but no response yet.

@propergent As for the missing icon, if you are hotlinking the icons directly from my demo this will happen anytime I move the icons, upload a new set, or change the url. It's advised that you download and host the web font yourself vs hotlinking from the demo as I don't guarantee that link to work forever (and it's not advised to hotlink files).

**Comment by vushe** [comment]
Thanks for explanations! Sure problem is on Yahoo's side. Hopefully they'll fix it soon.

**Comment by fleeting** [comment]
Just a quick update. I've heard from several people including the [uservoice topic](https://yahoo.uservoice.com/forums/207813-us-weather/suggestions/10740099-yahoo-weather-api-randomly-returns-old-data) that everything seems to be working again as expected. As far as I know nobody, including myself, got word back from Yahoo but I've tested a few times and looks like they fixed whatever the problem was.

Hopefully it's working again for all of you and continues to work.

**Comment by nbiuk** [comment]
It works! :D
