### ISSUE TITLE
simpleWeather problem with update time

### ISSUE THREAD

**Issue by DaddyBurrito** [monkeecreate/jquery.simpleWeather#158]
As I work on my simpleWeather page I noticed that each time I refreshed the page to see the impact of my CSS changes that the current temperature was fluctuating significantly. I added weather.updated and found that each time I refreshed the page it was coming back with a very different updated time. Sometimes the updated value would be as long ago as a week from the current time. I am building a digital sign and this page will be part of the rotation so it will get displayed/refreshed about once every 2 minutes or so. I need to make sure that the updated time is the most recent available from Yahoo and that the corresponding weather data is also correctly shown. My development is behind a firewall so I cannot expose the page but will be happy to share code here if needed.

**Comment by mosered** [comment]
I am noticing the same issues in my environment. Every time the web page is refreshed, it displays a different temperature, and the variance is quite different each time. Any help would be greatly appreciated.

**Comment by vushe** [comment]
Already discussed
https://github.com/monkeecreate/jquery.simpleWeather/issues/156

**Comment by fleeting** [comment]
Per #156, it's a known issue and I along with a few others have tried to contact Yahoo support about the problem but so far no response.
