### ISSUE TITLE
Lithuanian weather issue

### ISSUE THREAD

**Issue by AndriusLT** [monkeecreate/jquery.simpleWeather#160]
No matter what location i choose, my city = "Lithuania", not 'Vilnius' or 'Kaunas' or 'Klaipeda'. Geolocation doesn't help. Temperature unaccurate. In same minute temperature changes between 1 and 11 celsius.

**Comment by damien-a** [comment]
Hi James!
I use SimpleWeather for a newsroom website dedicated to winter conditions of Paris airports.
And in recent days, it seems that the plugin does not work, the values ​​are false and change with every page refresh.
Apparently all geographic request are impacted, as Austin Texas :-)
Could you try to correct this problem?
Thank you in advance,

Damien

**Comment by fleeting** [comment]
@damien-a See issue #156 for more. It's a known problem on Yahoo's end.

**Comment by damien-a** [comment]
Ok, I didn't know.
It seems to work perfectly now.
Thanks for the reply!

Damien
