### ISSUE TITLE
Returning[Object][Object]

### ISSUE THREAD

**Issue by mahsmmanu** [monkeecreate/jquery.simpleWeather#162]
Hello,

I am getting [object][object] when i select loaction:'Kathmandu, NP'. Also, I have tried woeid:'12742081'. But returning same issue.

Why is this happening??

**Comment by jacob418** [comment]
Same Problem here.
It just stopped working one Day.

**Comment by red5interactive** [comment]
You might have to change the woeid or location settings

**Comment by fleeting** [comment]
Yahoo's API was down for some time but seems to be working again now.
