### ISSUE TITLE
@ Letter Country Code not showing up - Full Country Name Instead

### ISSUE THREAD

**Issue by TerrenceLP** [monkeecreate/jquery.simpleWeather#164]
I'm using '+weather.country+' but to no avail, it still displays the Full Country Name. Unlike Region, ex: NC - that is working even in other countries.

![screen shot 2015-12-04 at 10 19 48 am](https://cloud.githubusercontent.com/assets/6816537/11593132/94e90c7e-9a70-11e5-8d92-efcffc7fe28a.png)

**Comment by fleeting** [comment]
Thanks for reporting this. It looks like Yahoo has changed what is returned as country and now returns the full country name instead of the abbreviated version. I'll update the website to reflect their change.
