### ISSUE TITLE
plugin is not working now

### ISSUE THREAD

**Issue by babygolden** [monkeecreate/jquery.simpleWeather#165]
https://query.yahooapis.com/v1/public/yql?format=json&rnd=201511115&diagnos…X%22%20and%20gflags=%22R%22%20limit%201)%20and%20u=%22f%22&_=1450078602019 Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by darkkean** [comment]
+1 same issue here.

**Comment by fleeting** [comment]
Are you guys still having problems with it? I'm currently not seeing any issue on the demos at http://simpleweatherjs.com/ or on [Yahoo's Weather API](https://developer.yahoo.com/weather/).
