### ISSUE TITLE
Heat index is always equal to the current temperature

### ISSUE THREAD

**Issue by Chimit** [monkeecreate/jquery.simpleWeather#170]
Yahoo API doesn't provide this value, so it's calculated by the simpleWeather script. I think, there is something is wrong.

**Comment by fleeting** [comment]
If the current temp is less than 80F and the humidity is less than 40, I just return the current temp as the heat index. I could be wrong and I'll look into it a little more but from what I saw heat index is only calculated if temps are 80+ and humidity is 40+ as seen in [this chart](https://en.wikipedia.org/wiki/Heat_index#Table_of_Heat_Index_values) and the [national weather service](http://www.nws.noaa.gov/om/heat/heat_index.shtml). My understanding was at 80F and 40% humidity the heat index is the same as the current temp (per the chart) and anything less than that also returns the current temp.

**Comment by Chimit** [comment]
As I know, heat index should also use the wind speed.

**Comment by fleeting** [comment]
@Chimit, from everything I have researched, heat index doesn't take into account actual wind speed, instead it assumes light wind by default. See both links in my last comment that go into more detail. It only takes into account relative humidity and current temperature.
