### ISSUE TITLE
Uncaught ReferenceError: html is not defined

### ISSUE THREAD

**Issue by felixdorner** [monkeecreate/jquery.simpleWeather#171]
Hey,

I have a problem to get the plugin running within a WP theme in a local dev environment:

- I call jQuery in the header
- I call jquery.simpleWeather.js in the footer
- I call the init script after the plugin script in footer (exactly like here: http://codepen.io/fleeting/pen/xwpar)
- I placed a div with the id="weather" in the templates
- I develop on a local server

In the console I get the following error (since I tried to run the plugin):
"Uncaught ReferenceError: html is not defined"

Do you have any idea how to solve the error? I am running out of ideas as I am not really a jQuery expert.

Cheers,
Felix

**Comment by jayharland** [comment]
"html is not defined" means exactly what it says, you're referencing a variable that hasn't been defined. 

Does your code look exactly like that codepen? If not, the variable "html" is defined on line 8. If you're defining it somewhere else, it could be a scope issue. I can only speculate though since I can't see it and the plugin is failing in general as of this moment.

Can you create a codepen with your code in it so we can see what's going on?

**Comment by felixdorner** [comment]
Thats my code: 

```javascript
$.simpleWeather({
    location: 'Berlin, DE',
    woeid: '',
    unit: 'c',
    success: function(weather) {
      html = '<p>'+weather.temp+'&deg;'+weather.units.temp+'</p>';
  
      $("#weather").html(html);
    },
    error: function(error) {
      $("#weather").html('<p>'+error+'</p>');
    }
});
```

I call some other scripts as well... they ran without errors before I enqueued simpleWeather.js. Can there be conflicts with such a generic variable like html? How can it happen that the variable is not defined?

**Comment by felixdorner** [comment]
I got it working because I changed the function:

```javascript
( function( $ ) {
  $.simpleWeather({
    location: 'Berlin, DE',
    woeid: '',
    unit: 'c',
    success: function(weather) {
      html = '<p>'+weather.temp+'&deg;'+weather.units.temp+'</p>';
  
      $("#weather").html(html);
    },
    error: function(error) {
      $("#weather").html('<p>'+error+'</p>');
    }
  });
} )( jQuery );
```

I am glad that it is now working, but I have no idea why? Maybe someone can explain it?

Cheers,
Felix

**Comment by aaronhb** [comment]
I had this same problem and had to use this.html and it fixed it since i was calling it in an external javascript file in a js folder. Hope this helps.
