### ISSUE TITLE
Location is no working

### ISSUE THREAD

**Issue by nikotz** [monkeecreate/jquery.simpleWeather#172]
hi In your web "http://simpleweatherjs.com/" show 

".simpleWeather({
    location: 'Austin, TX',
    woeid: '',"

the part of "location" not working only put woeid number whitout "location" works

**Comment by jayharland** [comment]
I second this. 

Normally it works but it's been throwing an error for about an hour now, when I try with just a test WOEID it works normally.

When it fails with location, it doesn't trigger the "error" function, it just straight up fails which kind of sucks... :/

**Comment by fleeting** [comment]
Yahoo's API was down for awhile which was causing the issue. The service seems to be back up right now. I'm going to release an update to catch the errors. Yahoo tends to change what they return for errors so I just need to make some tweaks.
