### ISSUE TITLE
jQuery simpleweather.min.js, GET https://query.yahooapis.com/v1/public/yql returns 'e.query.results is null'

### ISSUE THREAD

**Issue by Amatobahn** [monkeecreate/jquery.simpleWeather#176]
Was working fine just last night (January 18th, 2016). More than likely an issue with yahoo updating their weather API. Noticed there was a similar issue dated a few years ago here: [Previous issue](https://github.com/monkeecreate/jquery.simpleWeather/issues/100)

Attached code snippit I was using, and had previously working.
[weather.zip](https://github.com/monkeecreate/jquery.simpleWeather/files/96825/weather.zip)

Thanks.

**Comment by jonmrod** [comment]
Same problem here

**Comment by TheAmeoba** [comment]
I'm getting the same issue and it appears to also effect all the demos on simpleweather's own website

**Comment by fleeting** [comment]
See #174 for some temporary fixes and other information.
