### ISSUE TITLE
Widget is returning error:  There was an error retrieving the latest weather information. Please try again.

### ISSUE THREAD

**Issue by dadkind** [monkeecreate/jquery.simpleWeather#182]
Since January 19, 2016, our weather widget has been returning an error.

The error handling provided on your website was resulting in "[object] [Object]" being displayed.
Some debugging got us to display the message: "There was an error retrieving the latest weather information. Please try again."  
but nothing else.
What is the problem? Is our setup broken (it's been running for over one year)?
Any ideas are appreciated!
-dadkind

**Comment by fleeting** [comment]
See #174 for info.
