### ISSUE TITLE
SimpleWeather stopped working?  Its not working on http://simpleweatherjs.com/ either?

### ISSUE THREAD

**Issue by DigitalFusionTom** [monkeecreate/jquery.simpleWeather#183]
SimpleWeather stopped working on our website recently.  There are no errors, its just simply blank.  I went to http://simpleweatherjs.com/ and it seems its not working there either. 

Did something change on Yahoo's end or something?

**Comment by fleeting** [comment]
See #174 for info and temp fixes.
