### ISSUE TITLE
simpleWeather randomly stopped working

### ISSUE THREAD

**Issue by MegabyteRain** [monkeecreate/jquery.simpleWeather#186]
Ok, so I have been using simpleWeather for a while now and I even produced an app using it (it only has like 60 current downloads). The app worked fine and I was producing an update for it on my computer and simpleWeather was also working fine until one day I get this email from a user saying that my app had stopped working. I thought that was odd so I checked out the app on my phone and sure enough, it didn't work. Confused I went to my computer and the simpleWeather code had stopped working as well. I tried to debug and the console gave me this error when I tried to get weather from simpleWeather: "Uncaught TypeError: Cannot read property 'results' of undefined".
I went onto the simpleWeather.js website and not even the demo works! 
Why is this? When will it be fixed?

**Comment by fleeting** [comment]
See #174 for info and temp fixes.
