### ISSUE TITLE
"Cannot read property 'results' of undefined"

### ISSUE THREAD

**Issue by jpggvilaca** [monkeecreate/jquery.simpleWeather#187]
Did the yahoo weather api changed? now i'm not getting any weather results...i've used this package a couple of months ago and it worked perfectly. Now it throws this error...

**Comment by ecaste** [comment]
Hi, same problem here...

**Comment by puneet-sindhwani** [comment]
Same issue:

On Mozilla Firefox, I am getting
TypeError: data.query is undefined
	if(data !== null && data.query !== null && data.query.results !== null && data.q...

On Google Chrome, I am getting
Uncaught TypeError: Cannot read property 'results' of undefined

Please fix this, my client is killing me.

**Comment by ndwl** [comment]
Same for me too

**Comment by aplatt13** [comment]
I had the same issue. Fixed by changing the Yahoo API query:

from:

if(options.location !== '') {
        weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.placefinder where text="'+options.location+'" and gflags="R" limit 1) and u="'+options.unit+'"';
      }

to:

if(options.location !== '') {
    weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places where text="' + options.location + '" limit 1) and u="'+options.unit+'"';
}

Not sure if the Yahoo API changed or what, but it did the trick. Reference: https://developer.yahoo.com/weather/

**Comment by fleeting** [comment]
See #174 for info.

**Comment by ndwl** [comment]
Perfect, back up and running many thanks chaps.

Regards - Nick


Nick Loat  MA(RCA)
Loat Davies

-----------------------------------
The Old Rectory Studio
Bourton Road
Moreton-in-Marsh
Gloucestershire
GL56 0BG
-----------------------------------
T:  +44 (0) 1608 812883
F:  +44 (0) 1608 812881
M: +44 (0) 7970 024271
-----------------------------------
Company no. 3069120
Vat no. 628 4989 83
-----------------------------------
