### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'data.query.results')

### ISSUE THREAD

**Issue by aeflux** [monkeecreate/jquery.simpleWeather#189]
This is just something that happened recently. This was all working fine on a lot of our sites. But since Friday, Jan 22, it isn't functioning on any of our sites. It also isn't operating on http://simpleweatherjs.com
![screen shot 2016-01-25 at 2 01 44 pm](https://cloud.githubusercontent.com/assets/5324918/12562711/3f411c38-c36c-11e5-91bf-6f6d5c973ff7.png)

Any idea what is going on?

**Comment by fleeting** [comment]
See #174 for info.

**Comment by aeflux** [comment]
Thanks I did find that after I posted.
Jim Peck
Application Development
UI Developer Team Lead

www.maritztravel.com<http://www.maritztravel.com/>
ph: 636.827.2184
cell: 314.299.5339
email: jim.peck@maritz.com<mailto:jim.peck@maritz.com>
