### ISSUE TITLE
The plugin does not work from today?

### ISSUE THREAD

**Issue by shivanraptor** [monkeecreate/jquery.simpleWeather#190]
Been using this plugin for a year. Starting from today, the plugin stops working & displays the following error: 

> Uncaught TypeError: Cannot read property 'results' of undefined

This is also happening on the demo.

**Comment by AhmadHassanAwan** [comment]
facing this issue since last week.
please help..

**Comment by Elsenthil** [comment]
Hello

exactly the same problem for me like anyone else I guess...
Is this possible to fix this ? Thanks

**Comment by galetto** [comment]
Also facing the same issue from last week

**Comment by DaTebe** [comment]
I'm also facing this issue.

**Comment by mehmetafsinyuce** [comment]
I solved like this  (line 26)

Original 
weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.placefinder where text="'+options.location+'" and gflags="R" limit 1) and u="'+options.unit+'"';

Changed
weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="'+options.location+'") and u="'+options.unit+'"';

**Comment by AhmadHassanAwan** [comment]
@mehmetafsinyuce It worked for me too. Thank you.

**Comment by Elsenthil** [comment]
Same, it worked for me too. Thank you.

**Comment by DaTebe** [comment]
@mehmetafsinyuce 
It works! Very nice!

**Comment by fleeting** [comment]
See #174 for more info.
