### ISSUE TITLE
No results being returned

### ISSUE THREAD

**Issue by sccr410** [monkeecreate/jquery.simpleWeather#191]
Looks like this plugin no longer works? We have been using this for over a year perfectly but suddenly stopped working last week. Checked your site and all your demos are broken as well returning the same JS error: "Uncaught TypeError: Cannot read property 'results' of undefined"

**Comment by fleeting** [comment]
See #174 for info.

**Comment by sccr410** [comment]
Yep, sorry for the new ticket - got it resolved
