### ISSUE TITLE
weather js stopped working

### ISSUE THREAD

**Issue by edimarsky** [monkeecreate/jquery.simpleWeather#192]
nothing changed on my side. just stopped working. when I put Chicago, IL on you demo website nothing works either...

**Comment by jsgilly20** [comment]
Same issue here, running weather on a couple of sites and stopped working some time in the last 24 hours. 

Console log error is saying: Uncaught TypeError: Cannot read property 'results' of undefined in jquery.simpleWeather.min.js:2

My guess is the hosted file has been modified and it's now broken. Changing to a self hosted version might fix this.

**Comment by HappyTepid** [comment]
Same here, mine is hosted locally and returns nothing, console displays `Uncaught TypeError: Cannot read property 'results' of undefined`, I suspect the issue lies with Yahoo's API.

**Comment by fleeting** [comment]
See #174.
