### ISSUE TITLE
SimpleWeather not returning any data

### ISSUE THREAD

**Issue by vaskar-nepal** [monkeecreate/jquery.simpleWeather#193]
It was working till yesterday, now it does not return anything. On console I see 
TypeError: e.query is undefined

Also get this on response

:"Tenant 'query_yahooapis_com' access to 'Resource [tenantName=query_yahooapis_com, type=TABLE, name
=geo.placefinder, locatorType=FILE, url=/home/y/share/manhattan/application/tenantBundles/yql_query_yahooapis_com_manhattan_v2
/YQL-INF/restdefs/geo.placefinder.xml, useUrl=false]' is denied."}});
GET yql?format=json&rnd=2016...%22f%22&_=1453893413022

**Comment by SnooHD** [comment]
I had the same issue; i checked the yahoo API and it seems that the SQL that is used in the script is a bit different.

In simpleweather.js, on line 26 find "geo.placefinder" and replace it with "geo.places(1)".
Did the trick for me ;)

**Comment by vaskar-nepal** [comment]
Tried this too didn't work.

**Comment by HappyTepid** [comment]
Didn't work for me either.

**Comment by fleeting** [comment]
See #174.
