### ISSUE TITLE
No weather displaying.

### ISSUE THREAD

**Issue by islanddog** [monkeecreate/jquery.simpleWeather#195]
Morning All; I utilized a WordPress theme by @natejones to build a custom Digital Signage Solution (@natejones/wpds). In the last 5 days the Weather Widget has stopped working. The widget is based off of SimpleWeather so I came here in an attempt to grab a fix. It does not display an error or issue however if I go to simplyweatherjs.com all the demos do not have a temp present. Has the plugin become out of sync? Does anyone have a fix? I can post whatever information or coding you need.

**Comment by joe8104** [comment]
Hello,

This is my first post on Github, I've just registered here to be able to let you know that I am having the same problem as islanddog.

The widget was working fine before couple of days and suddenly stop working. Can you, please, check it out and say if you can fix it (maybe it is some big yahoo changes) or we have to search for another solution? This is the site with widget in use - www.tsarevo.info

Thank you in advance.

**Comment by fleeting** [comment]
See #174 for info.
