### ISSUE TITLE
Uncaught TypeError: Cannot read property 'results' of undefined

### ISSUE THREAD

**Issue by pazzypunk** [monkeecreate/jquery.simpleWeather#196]
![image](https://cloud.githubusercontent.com/assets/44990/12679621/2ba7398c-c673-11e5-811b-741bbd975275.png)

I'm not getting any results any more on my site (I first noticed this yesterday). It looks like it's broken on the demo page, too. It looks like it's not returning any data from Yahoo.

**Comment by fleeting** [comment]
See #174 for info.
