### ISSUE TITLE
simpleWeather is not displaying data any more

### ISSUE THREAD

**Issue by studio11** [monkeecreate/jquery.simpleWeather#197]
simpleWeather is not displaying data any more even on your demo.
Can you help

**Comment by fleeting** [comment]
See #174.

**Comment by studio11** [comment]
this is not it :(
http://simpleweatherjs.com/ demo is not working also.
I tested on MAC in FF, Safari, Chrom and iPhone

**Comment by fleeting** [comment]
Yeah, the demos are down due to the changes Yahoo has made per #174. The temp fixes in there should work for you.
