### ISSUE TITLE
If using a location string yahoo returns null.

### ISSUE THREAD

**Issue by hexchaimen** [monkeecreate/jquery.simpleWeather#198]
For anyone using not using geolocation; rather the simple location, for instance  'Austin, TX' will return null results from yahoo and simpleWeather will not error out.  Instead locate WOEID for the location until fix. 

[http://codepen.io/anon/pen/obybBy](http://codepen.io/anon/pen/obybBy)

**Comment by fleeting** [comment]
See #174 for info.
