### ISSUE TITLE
Cannot read property 'results' of undefined

### ISSUE THREAD

**Issue by larsinsd** [monkeecreate/jquery.simpleWeather#200]
I'm seeing this for all locations with 3.1.0 (it was also doing it with 3.0.2).  Any ideas why? 

It is getting a Javascript error I can see in the Chrome console.  It is pointing to the line where it looks for e.query.results in the minified version.

** Cannot read property 'results' of undefined
**
The actual Javascript for the call is:

		$.simpleWeather({
			location: "San Diego, CA, United States",
			woeid: '',
			unit: 'f',
			success: function(weather) {
				var html = '';
				if ((weather.code == 31) || (weather.code == 33)) // night clear or fair
				{
					html = '<img src="/images/weather_clear_night.png" style="vertical-align: middle;" />';
				}
				else if ((weather.code == 27) || (weather.code == 29)) // night partly or mostly cloudy
				{
					html = '<img src="/images/weather_clouds_night.png" style="vertical-align: middle;" />';
				}
				else if ((/storm/i.test(weather.currently)) || (/hail/i.test(weather.currently)) || (/hurricane/i.test(weather.currently))  || (/tornado/i.test(weather.currently)))
				{
					html = '<img src="/images/weather_thunderstorms.gif" style="vertical-align: middle;" />';
				}
				else if (/snow/i.test(weather.currently))
				{
					html = '<img src="/images/weather_snow.gif" style="vertical-align: middle;" />';
				}
				else if ((/rain/i.test(weather.currently)) || (/shower/i.test(weather.currently)) || (/drizzle/i.test(weather.currently)) || (/sleet/i.test(weather.currently)))
				{
					html = '<img src="/images/weather_rain.gif" style="vertical-align: middle;" />';
				}
				else if ((/partly/i.test(weather.currently)) && (/cloudy/i.test(weather.currently)))
				{
					html = '<img src="/images/weather_partlycloudy.gif" style="vertical-align: middle;" />';
				}
				else if (((/partly/i.test(weather.currently)) || (/mostly/i.test(weather.currently))) && ((/sunny/i.test(weather.currently)) || (/clear/i.test(weather.currently))))
				{
					html = '<img src="/images/weather_mostlysunny.gif" style="vertical-align: middle;" />';
				}
				else if (/cloud/i.test(weather.currently))
				{
					html = '<img src="/images/weather_cloudy.gif" style="vertical-align: middle;" />';
				}
				else if (/windy/i.test(weather.currently))
				{
					html = '<img src="/images/weather_windy.png" style="vertical-align: middle;" />';
				}
				else if ((/sun/i.test(weather.currently)) || (/clear/i.test(weather.currently)) || (/fair/i.test(weather.currently)) || (/hot/i.test(weather.currently)))
				{
					html = '<img src="http://www.myteamcaptain.com/images/weather_sunny.gif" style="vertical-align: middle;" />';
				}

				html += '&nbsp;'+weather.temp+'&deg;'+weather.units.temp+'&nbsp;'+weather.currently;

				$("#contactWeather").html(html);
			},
			error: function(error) {}
		});

**Comment by Kalizo** [comment]
I have the same error "Uncaught TypeError: Cannot read property 'results' of undefined" : Yahoo has changed his API ?

**Comment by fleeting** [comment]
Can you both confirm you are using `v3.1.0`? I'm not getting any errors on the demos using either a city/state or geolocation.

**Comment by Kalizo** [comment]
I use the 3.0.2 version but since here, I never had any problem. Furthermore, on demo site http://simpleweatherjs.com it seems broke...

**Comment by fleeting** [comment]
`v3.0.2` has been broken for about a week or so as Yahoo removed one of their API endpoints, see #174 for info. This has been fixed in `v3.1.0`. I'm not getting errors on the demo. You will need to update your copy to the latest 3.1 though.

**Comment by larsinsd** [comment]
Yes - I'm on 3.1.0 and it is still doing it, at least with the minified version.

**Comment by larsinsd** [comment]
Aha - wait - I just got the raw version down from here and now it works.  Not sure if you did something or I did, but it looks to be working now.

And in case you haven't heard it recently, THANK YOU for making this plugin.  It's awesome and an important part of our user experience.

**Comment by fleeting** [comment]
Awesome, glad it's working now! I didn't do anything so might have just needed an update or might have been cached on your end. Let me know if there are any other issues. Thanks!

@Kalizo If you still have issues after updating to `v3.1.0` let me know.
