### ISSUE TITLE
Weather.link is broken 

### ISSUE THREAD

**Issue by michael72653** [monkeecreate/jquery.simpleWeather#202]
I updated to your latest version of simpleWeather 3.1.0, but I also noticed that the weather.link is broken. Yahoo! must of changed their redirect for this too. Is it possible to update it in the code?

**Comment by fleeting** [comment]
That's the link that Yahoo gives in their API. I'm looking at a work around but ultimately it's something that I've been waiting for Yahoo to fix on their end, going on over a year now though.
