### ISSUE TITLE
zipcode by itself no longer working?

### ISSUE THREAD

**Issue by webdevbrian** [monkeecreate/jquery.simpleWeather#204]
Hey gents, love the lib.  Before updating to 1.9 I was able to just pump in a zip and it'd work. For whatever reason just supplying a zip now doesn't work, it doesn't error or out or anything but there's no success callback. I had to update a few dashboard widgets I'm using this on to now run off of city or town + state e.g.,: 'Bangor, ME'.

Let me know if anyone else has this issue or can reproduce. If not I'll keep diagnosing, but the only thing I did was update my lib.

Thanks!

**Comment by fleeting** [comment]
Have you tried updating to `v3.1.0`? I'm able to get a zip code working on the demos so I would need to see a link or your code to see the issue.

**Comment by webdevbrian** [comment]
I actually updated to 3.1 and it broke, so yeah

http://d.pr/v/1ipxW

code it use to be : 

```
  $.simpleWeather({
    zipcode: '06798', // 'Woodbury, CT'
    success: function(weather) {
```

code it is now:

```
  $.simpleWeather({
    location: config.myLocation, // 'Woodbury, CT'
    success: function(weather) {
```

**Comment by fleeting** [comment]
You should be using `location` instead of the old `zipcode` option (which was replaced awhile back). You just put the zip code in `location`. Based on your video it should be `location: '06798',`

**Comment by webdevbrian** [comment]
ah - yeah I had a pretty old lib then. You da man @fleeting :+1:
