### ISSUE TITLE
Specialize the class and div names to avoid clashes when used with other projects

### ISSUE THREAD

**Issue by electronicsguy** [monkeecreate/jquery.simpleWeather#205]
Hi,
  Love your work on simple weather. I modified it to specialize the class and div names to avoid clashes with other elements with the same class.  Modified the CSS slightly so it adjusts for multiple weather divs on the same page. I also created a function to easily call the weather function for multiple divs.

You can find the modified main .html file here: [SimpleWeather.html](https://github.com/electronicsguy/MereScripts/blob/master/General/SimpleWeather.html)

All credits to you.

**Comment by fleeting** [comment]
Nice! It is intended that you use your own classes, divs, and CSS. `simpleWeather` includes none of that by default. What is shown are just example demos that I worked up; none of the HTML, CSS, or class names are required from them.
