### ISSUE TITLE
There was a problem retrieving the latest weather information.

### ISSUE THREAD

**Issue by vimorozov** [monkeecreate/jquery.simpleWeather#206]
Any idea why ?

**Comment by georgekaf** [comment]
Yahoo service is unavailable maybe?
https://github.com/monkeecreate/jquery.simpleWeather/issues/174#issuecomment-180872480

**Comment by fleeting** [comment]
Yahoo's API was down. It seems back up now.

**Comment by oligalma** [comment]
I have the same problem. A library with this issue is completely useless.

**Comment by fleeting** [comment]
@oligalma I completely agree. See #221 for information.

**Comment by oligalma** [comment]
Do you know how to get the weather using PHP? In this page (http://99webtools.com/blog/get-weather-information-using-php) says that is possible with Open Weather Map. But I tried the example code and I get a "Unauthorized" error, I don't know why...

**Comment by fleeting** [comment]
Open Weather Map now requires registering and using an API key (free and paid plans at http://openweathermap.org/price). Looks like that post is just out dated. That type of question would be better fit for http://stackoverflow.com though since that post isn't something I have anything to do with.
