### ISSUE TITLE
Plugin no longer working

### ISSUE THREAD

**Issue by vdecree** [monkeecreate/jquery.simpleWeather#208]
Hi there,

I've only just notice but the plugin has stopped working. Has there been updates the Yahoo api that could of broke things? And are you planning on updating the plugin at any point? 

Many thanks
M

**Comment by mrhaw** [comment]
Why did you close this issue without answer? My plugin are down on multiple pages :(

**Comment by fleeting** [comment]
I'm not sure why he closed it, I assume he noticed the recent update or other issues. Yahoo made a change to their API and removed one of the end points I was using, `v3.1.0` fixes this.
