### ISSUE TITLE
Heat index is 286.43442974000004° C

### ISSUE THREAD

**Issue by chimit** [monkeecreate/jquery.simpleWeather#210]
I have current temperature -3° C and heat index 286.43442974000004° C.
Humidity is 39%.
Wind is 11.27 km/h.

**Comment by fleeting** [comment]
Hmm, I'll take a look at this. It should just return -3 as the heat index since you can't calculate a heat index for anything below 26.7 C.

**Comment by drtonyb** [comment]
This is easily fixed. Firstly, the if statement on line 76 is the wrong way around. The heat index equation only applies when temperature is > 80F and humidity is > 40% - you have the opposite. Secondly, the heat index equation requires the temperature in F, but when Celsius units are selected, the temperature is in C, so the heat index calculation is completely wrong.
