### ISSUE TITLE
Not showing accurate city name

### ISSUE THREAD

**Issue by nsohail** [monkeecreate/jquery.simpleWeather#212]
I am using geolocation to get coordinates for my current location and on Google Maps it shows the correct city name when I plugin the coordinates but simpleWeather gives me a weird city name. I am located in Adams Morgan, Washington DC and the city name I keep getting is Pretty Prospect, DC. I have never heard of this area.

**Comment by fleeting** [comment]
Can I get the exact coordinates it is using?

**Comment by nsohail** [comment]
38.9215776,-77.04301029999999

**Comment by fleeting** [comment]
Unfortunately that's the result Yahoo returns when looking up those coordinates; Pretty Prospect, DC historical town. This would be an issue with Yahoo's data vs simpleWeather. Here is the data Yahoo returns https://developer.yahoo.com/yql/console/#h=select+*+from+geo.places+where+text%3D%22(38.9215776%2C-77.04301029999999)%22.

**Comment by nsohail** [comment]
Are all coordinates returning a historical city name? I tried other major cities and they all return an unfamiliar city name. Is there a setting I can change on my end to fix this?

**Comment by fleeting** [comment]
I haven't seen other cases of this happening but it could. I tried with a handful of cities and my local coordinates which returned Boston, MA as expected.
