### ISSUE TITLE
Cache Issue?

### ISSUE THREAD

**Issue by kraymitchell** [monkeecreate/jquery.simpleWeather#214]
I am trying to change some layout options, font sizes, margin, etc.

However, I make the change directly to the file on the webserver and even in a new Incognito/Private window the changes don't reflect. I've tried clearing cache and SHIFT+Refresh with no luck.

Am I doing something wrong?

**Comment by fleeting** [comment]
I'm not really sure what this means or how it relates to simpleWeather.

**Comment by kraymitchell** [comment]
Uhhhh.... because when I make a change to simpleWeather CSS files, I don't see the changes when viewing the simpleWeather HTML file that displays the information.

I should be able to make a change (like I do with other files on the same server) and see the changes reflected. So I am asking if there is something with a cache you've put into simpleWeather that is causing this.

**Comment by fleeting** [comment]
Nothing should be cached but simpleWeather doesn't have any CSS or HTML, it's just a jQuery plugin that returns weather data. The demo has some CSS and HTML but simpleWeather itself is just a single JavaScript file.

**Comment by kraymitchell** [comment]
That maybe so, but without the HTML and CSS then it's pretty useless by itself. It's not pretty without those items, and people want pretty. 

Back to the drawing board I guess.

**Comment by fleeting** [comment]
I get that but simpleWeather is ultimately just a wrapper for the Yahoo Weather API. It simply returns the weather data for you to then apply your own HTML and CSS as needed. The stylized demos were just to show some possible examples of how the data could be used more vs that is what they should look like. Sorry I couldn't help.

**Comment by kraymitchell** [comment]
And all I was asking is if there were any known caching issues that would cause me not to see the changes I make. 

Since the only thing on the server I cannot see my changes with is this one JS solution, I thought there might be something in the JS causing it that I wasn't aware of as I don't JS. Trying to cover all my bases.
