### ISSUE TITLE
return image

### ISSUE THREAD

**Issue by AaronHoaNguyen** [monkeecreate/jquery.simpleWeather#215]
The return image is not correct for Bradford UK. It's return day instead of night.

**Comment by fleeting** [comment]
This is correct. Yahoo's API doesn't actually return the image as easy to use so I just pull from Yahoo's Weather icons and pull whatever matches the condition code. I don't check against time of day. I guess I could check the `last_updated` field against the `sunset` and `sunrise` fields to try and return a night version, if there is one.

I'll add it to my to do list. Thanks!
