### ISSUE TITLE
Displaying Wind Speed in Knots

### ISSUE THREAD

**Issue by trex888** [monkeecreate/jquery.simpleWeather#216]
Hi there,

Is it possible to display the wind speed in Knots instead of mph or kms? If so, how would I go about doing so?

Thanks for any help with this,

T

**Comment by fleeting** [comment]
This isn't currently available but it's something I can look at adding soon. If the meantime, it's a simple equation you can do on your own for simpleWeather. 1 mph is 0.869 knots, so just take the mph wind speed and multiply it by 0.869. Something like `knots = wind.speed * 0.869;`. If you use kph then it's 0.540.

**Comment by trex888** [comment]
Hi again,

Thanks for the tip. Can't quite make it work though. Of all SimpleWeather's functionality, I'm just using the following 3 calls:

`  html = '<p>'+weather.temp+'&deg;'+weather.units.temp+'</p>';
      html += '<p>'+weather.wind.direction+' '+weather.wind.speed+'kts</p>';`

Where exactly am I to put your equation in order for weather.wind.speed to display in knots?

Thanks for any further help with this,

T

**Comment by fleeting** [comment]
No problem. Here is a quick demo; what you want is line 12 of the JavaScript. http://codepen.io/fleeting/pen/NNdqaW That assumes the speed is mph, if it's not then just switch out the number to the opposite from above.

**Comment by trex888** [comment]
Wow that's fantastic, thanks! 

Hope I'm not pushing it but can I ask how I'd go about making the wind speed output without any decimal places, as in rounding the number either up or down? Currently it's displaying like this: 

E 19.116kts. 

Where 19.116kts is displayed, I'd like it to just show as 19kts. Thoughts?

Thanks again,

T

**Comment by fleeting** [comment]
Yep, [`Math.round()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round) is what you are looking for. Check the example again - http://codepen.io/fleeting/pen/NNdqaW.

**Comment by trex888** [comment]
Fantastic! Thanks so much for your help. Really appreciate it. Think I'm all set now.

Best,

T
