### ISSUE TITLE
Trouble getting it to work on Wordpress

### ISSUE THREAD

**Issue by trex888** [monkeecreate/jquery.simpleWeather#217]
Hi there,

Having trouble getting the plugin to work on Wordpress and hoping you might be able to advise on where I've gone wrong. So far, I've uploaded the jquery.simpleWeather.js file to my root directory, then add the following to my child themes header.php file:

` $(document).ready(function() {
  $.simpleWeather({
    location: '43.623432, -79.386583',
    woeid: '',
    unit: 'c',
    success: function(weather) {
      html = '<p>' + weather.temp + '&deg;' + weather.units.temp + '<br />' + weather.wind.direction + ' ' + Math.round(weather.wind.speed * 0.540) + 'kts</p>';

      $("#weather").html(html);
    },
    error: function(error) {
      $("#weather").html('<p>' + error + '</p>');
    }
  });
});`

Then added `<div id="weather"></div>` to the page I wish to have weather displayed, but nothing displays. What have I missed here?

Thanks for any help with this,

T

**Comment by fleeting** [comment]
I would need to see a link to see any errors. You should also make sure that the simpleWeather script and code is loaded after jQuery.

**Comment by trex888** [comment]
Here's a link: [click here](http://www.anchoredmedia.ca/iyc/home-test/)

I'm just trying to add it to a blank test page for now. Once it displays accordingly, I'll be putting it on the bottom of the nav, where there is currently static text displaying temperature, wind direction and wind speed.

**Comment by fleeting** [comment]
Looks like you didn't include the simpleWeather script. You might have uploaded `jquery.simpleWeather.js` but it will need to be included after jQuery but above the simpleWeather code calling it. I'm not sure how the theme/child theme handles it so it could be just adding the `<script src="..."></script>` to the header or you could always use the CDN and add `<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.simpleWeather/3.1.0/jquery.simpleWeather.min.js"></script>` to the header.

**Comment by trex888** [comment]
I am lost...

Is there a step by step specific to Wordpress posted anywhere that you can recommend? I found 2, both listed completely different steps and neither seemed to work for me.
