### ISSUE TITLE
Hire your services for simpleWeather Wordpress integration

### ISSUE THREAD

**Issue by trex888** [monkeecreate/jquery.simpleWeather#218]
Hi Fleeting,

Wondering if I might be able to hire your services for a quick simpleWeather Wordpress integration? Not looking for anything beyond adding it to wordpress and having temp, wind direction and wind speed displayed. Simple job for you I'm sure, for me...that's another story. Let me know and if so, perhaps you can indicate a more private way to communicate the details?

Thanks for you consideration,

T

**Comment by fleeting** [comment]
Honestly I wouldn't have the time. Best bet would be posting what you have and what isn't working to stackoverflow.com for some help.
