### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by conntagious** [monkeecreate/jquery.simpleWeather#219]
I get the following error "There was a problem retrieving the latest weather information". I see your Demo is also not working. Thanks

**Comment by michael72653** [comment]
i get the same error too. please help.

**Comment by fleeting** [comment]
This would be an issue with Yahoo. The demos are working right now though.

**Comment by conntagious** [comment]
It's working again. Must have been momentarily, and I happened to be on the website at that moment! Thx
