### ISSUE TITLE
Yahoo Weather started enforcing OAuth 1 starting March 15, 2016.

### ISSUE THREAD

**Issue by equatebrand** [monkeecreate/jquery.simpleWeather#220]
simpleWeather now appears to be broken because of this.  Simply removing the /public/ part of the 

https://query.yahooapis.com/v1/public/yql?format=json&rnd="+o.getFullYear()+o.getMonth()+o.getDay()+o.getHours()+"&diagnostics=true&callback=?&q=....

line did not seem to fix it, either.

**Comment by equatebrand** [comment]
Never mind, seems to be fixed.

**Comment by fleeting** [comment]
You are correct that they are enforcing oAuth now. This presents a big problem for simpleWeather as you would have to make your consumer and secret API keys public which shouldn't be done. I'm looking into other API options but could be a little bit.

Also, simpleWeather seems to be working on the demos at the moment.
