### ISSUE TITLE
VM3145:2 Uncaught TypeError: Cannot read property 'results' of undefined

### ISSUE THREAD

**Issue by woosungchu** [monkeecreate/jquery.simpleWeather#222]
is it working now?

**Comment by quartsZzz** [comment]
I have not worked too

**Comment by quartsZzz** [comment]
I have the same error

**Comment by krugerz89** [comment]
Same here, according to an earlier post yahoo have changed their api security to OAuth,
"To increase the security measure and better serving our YDN customers, weather data source will enforce OAuth 1 starting March 15, 2016. Please update your API calls with OAuth 1 enabled (via the OAuth /v1/yql end point if using YQL) using your Yahoo App key and secret."

**Comment by githubthom** [comment]
I tried to create an app on https://developer.yahoo.com/apps/create/ but it doesn't let me do that (error message with no content). Seems broken at the moment.

**Comment by canomi** [comment]
who can fix it? please Let me how to fix it, many thanks

**Comment by portimo** [comment]
Same problem here. Does anyone have contact to Yahoo, to ask them to keep the API open?

**Comment by bitorbit** [comment]
Same here.

**Comment by richgcook** [comment]
Same.

**Comment by slivvy** [comment]
Same

**Comment by rwebler** [comment]
Created a PR that will at least bypass the result, instead of resulting in a TypeError: https://github.com/monkeecreate/jquery.simpleWeather/pull/223

**Comment by mikejmoran** [comment]
Same problem here. Any luck anyone?

**Comment by fleeting** [comment]
See https://github.com/monkeecreate/jquery.simpleWeather/issues/221#issuecomment-200832163.

**Comment by richgcook** [comment]
Is this really a suitable reason to close?

**Comment by fleeting** [comment]
@richgcook yes, since there is another issue open for it not working it's easier to keep all conversation about it to a single thread so everybody can find information easier.

**Comment by richgcook** [comment]
Oh sorry... didn't know it was because you wanted to keep it in a single thread... my bad :flushed:
