### ISSUE TITLE
Changing wind direction output

### ISSUE THREAD

**Issue by trex888** [monkeecreate/jquery.simpleWeather#224]
Using the code below, I get the following:

0°C
70
25kts

The 70 is wind direction. Can anyone advise as to what I need to add to the below code in order to have the wind direction display as: N, NW, SW, etc.? I figure I need to change +weather.wind.direction+ to +weather.wind.compass+ but of course "compass" needs to be defined and I'm not sure how to do that. This is what I'm using:

`var zipCode = 90210;

$.ajax({
    dataType: "json",
    headers:  { "Accept": "application/json; odata=verbose" },
    url: "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20geo.places%20where%20text%3D"+zipCode+"%20limit%201&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",
    beforeSend: function(xhr){xhr.setRequestHeader('Accept', 'application/json; odata=verbose');},
    success: function(data){
        $.getJSON("https://query.yahooapis.com/v1/public/yql?callback=?", {
            q: "select * from xml where url=\"https://weather.yahooapis.com/forecastrss?w=26332345&d=1&u=c\"",
            format: "json"
        },function (data) {       
	  var weather = data.query.results.rss.channel;
          var html = '<div>'+weather.item.condition.temp+'<span class="degree">&deg;</span>'+weather.units.temperature+'<br>'+weather.wind.direction+'<br>'+Math.round(weather.wind.speed*0.540)+'kts</div></a>';
          $("#weather").html(html);
        });
    },
});`

Thanks for any help with this,

T

**Comment by fleeting** [comment]
Line 50 and line 74 is how I do it with simpleWeather - https://github.com/monkeecreate/jquery.simpleWeather/blob/master/jquery.simpleWeather.js#L50

**Comment by trex888** [comment]
Adding those to lines to the code I'm using in my first post breaks the functionality, displaying no weather at all. Is there somewhere specific that I need to add those 2 lines or perhaps add something either before or after the 2 bits of code?

**Comment by fleeting** [comment]
I would need to know what error it's throwing. As you aren't using simpleWeather not sure if you will be able to just copy/paste those two lines or might have to make some tweaks. Depends on the code you are using.
