### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by biapar** [monkeecreate/jquery.simpleWeather#225]
From a while, I've this error:

Authentication Error.  The table weather.forecast requires a higher security level than is provided, you provided ANY but at least APP is expected

Link: [https://query.yahooapis.com/v1/public/yql?format=json&rnd=20162420&diagnostics=true&callback=jQuery1111022356682123317873_1458846165819&q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text=%22Paestum,%20CMP%22)%20and%20u=%22c%22&_=1458846165820](url)

**Comment by fleeting** [comment]
Yahoo recently made changes to their weather API to require OAuth. See #221 for details and some temp solutions.
