### ISSUE TITLE
Simple weather only in farenheit ? 

### ISSUE THREAD

**Issue by vimorozov** [monkeecreate/jquery.simpleWeather#226]
Hi, any idea why simple weather only display the weather in farenheit ?

**Comment by woosungchu** [comment]
Yahoo has made some changes to their API . So I guess that is temporary solution.

**Comment by biapar** [comment]
+1

**Comment by KibGim** [comment]
+1

**Comment by biapar** [comment]
The yahoo api work now on public url.

**Comment by biapar** [comment]
Simple workaround

Unit=c
temp = F temperature
`function getMyAltTemp(unit, temp) {
    if(unit === 'c') {
      return Math.round((5.0/9.0)*(temp-32.0));
    } else {
      return Math.round((9.0/5.0)*temp+32.0);
    }
  }	`

**Comment by maninderx** [comment]
Celsius also not displaying for my WOEID

**Comment by carrillo455** [comment]
As the bug is only displaying Farenheit, I came to this solution:

```
// Based on @biapar answer (y)
var getCelsius = function (temp) {
    return Math.round((5.0/9.0)*(temp-32.0));
};

var isFarenheitBug = weather.units.temp === "F";
if (isFarenheitBug) {
    weather.temp = getCelsius(parseInt(weather.temp));
    weather.units.temp = "C";
}
```

Hope its useful :)

**Comment by sleddogrob** [comment]
Celsius seems to be working with the exception of "wind chill" ( feels like ). I really hate asking but I don't suppose someone could point methe right direction for a work around for this? Been banging my head for a few days now on this one with no luck .
