### ISSUE TITLE
This script doesn't work on LG Smart TV

### ISSUE THREAD

**Issue by thejavibsd** [monkeecreate/jquery.simpleWeather#228]
Hi, im using this script to create a mini widgets to display some weather places on a dashboard that i use to present information on the LG Smart TV, it uses Netcast 4.0.
(ref http://developer.lge.com/webOSTV/discover/webostv-vs-netcast/).

I not a very dev person, but somehow i created an HTML Dashboard to present videos, slide news, dollar conversion, weather. Last time i used "zweatherfeed" script, but Yahoo had some changes and this is no longer working. So googl'n i found this SimpleWeather that is awesome, easy to configure. But this SmartTv i think cant deploy the jquery or some code.

Cheers!

**Comment by fleeting** [comment]
Honestly I'm not familiar with the smart TV or Netcast. Your best bet would be posting over on http://stackoverflow.com/ to get help from those who do have experience with it.
