### ISSUE TITLE
Error: "THERE WAS A PROBLEM RETRIEVING THE LATEST WEATHER INFORMATION."

### ISSUE THREAD

**Issue by kthornbloom** [monkeecreate/jquery.simpleWeather#231]
Awesome plugin! However I'm seeing this error both in my project, and on your demo page:
THERE WAS A PROBLEM RETRIEVING THE LATEST WEATHER INFORMATION.

Hopefully just a temporary disruption?

**Comment by kthornbloom** [comment]
closing.. seems to be working now

**Comment by asoomar** [comment]
Can you paste your js code here because mine seems to not be working either?
