### ISSUE TITLE
weather.wind.chill is showing temp in fahrenheit

### ISSUE THREAD

**Issue by rhkiyani** [monkeecreate/jquery.simpleWeather#232]
I have set unit : 'c' but wind.chill is coming as fahrenheit. All other temp values are fine.

![weather](https://cloud.githubusercontent.com/assets/4613909/14353743/73c887be-fca8-11e5-8bd1-ddfe0d36d279.JPG)

**Comment by fleeting** [comment]
Looks like bad data from Yahoo in this case. I just did a quick test in their [YQL Console](https://developer.yahoo.com/yql/console/?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22boston%2C%20ma%22)&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys#h=select+*+from+weather.forecast+where+woeid+in+(select+woeid+from+geo.places(1)+where+text%3D%22boston%2C+ma%22)+and+u%3D%22c%22) and the wind chill doesn't seem to change units. Best bet is to do the calculation to convert that into C. However, if Yahoo ultimately fixes the returned data then that would need to be removed or you would have wrong info again.

**Comment by rhkiyani** [comment]
I am doing quick conversion from F to C. Thanks.
