### ISSUE TITLE
Temperatures not matching

### ISSUE THREAD

**Issue by kmaier** [monkeecreate/jquery.simpleWeather#234]
Temperatures seem drastically off at times, I have a preview attached with a slight difference. 

Any insight on why they would be different when they are using the same service?
![temp](https://cloud.githubusercontent.com/assets/4949992/14608734/88246c76-054c-11e6-8e62-da395da0a82c.jpg)

Thank you!

**Comment by fleeting** [comment]
My guess is just how often Yahoo refreshes the API data.
