### ISSUE TITLE
Possible to display current time?

### ISSUE THREAD

**Issue by mcfaddengavender** [monkeecreate/jquery.simpleWeather#240]
Is it possible to display the current local time? This would be a big help!

**Comment by asoomar** [comment]
It is possible, and I have already done it. This is in the script section: ` <script>
function startTime() {
    var today = new Date();
    var h = today.getHours();
    var m = today.getMinutes();
    var s = today.getSeconds();
    m = checkTime(m);
    s = checkTime(s);
    var hours =
    ["12","1","2","3","4","5","6","7","8","9","10","11","12","1","2","3","4","5","6","7","8","9","10","11"];

    var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];

    var months =
    ["January","February","March","April","May","June","July","August","September","October","November","December"];

    var ampm = "";

    if(today.getHours<12)
    {
        ampm = "AM";
    }
    else
    {
        ampm = "PM";
    }

    var blinkSec = " ";

    if(s%2 != 0)
    {
        blinkSec= ".";
    }

    else
    {
        blinkSec= "..";
    }

    document.getElementById('txt').innerHTML =
    hours[h] + ":" + m + " " + ampm;

    document.getElementById('sec').innerHTML = blinkSec;

    document.getElementById('date').innerHTML =
    days[today.getDay()] + ", " + months[today.getMonth()] + " " + today.getDate() + ", " + today.getFullYear();

    var t = setTimeout(startTime, 500);
}

function checkTime(i) {
    if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
    return i;
}
</script>`

And this part is in the body:
`    <div id="sec" style="color: red;text-align: center; font-family: helvetica;font-size: 30px;"></div>
    <div id="txt" style="color: white; text-align: center; font-family: helvetica; font-weight: normal; font-size: 90px;"></div>
    <div id="date" style="color: white;text-align: center; font-family: helvetica;font-size: 30px;"></div>`

**Comment by fleeting** [comment]
Just to note for anybody who finds this. This would only give the current local time of the person visiting the page as it's client side JavaScript. It wouldn't give the local time of the weather. If the weather is for Seattle but I visit from Boston, it would show my time, not the local time in Seattle.
