### ISSUE TITLE
plugin won't display anything

### ISSUE THREAD

**Issue by perryodical** [monkeecreate/jquery.simpleWeather#241]
The code i wrote worked this morning and now it won't display anything. Went to the simpleweatherjs.com website as well and the same issue persists there.
http://codepen.io/perrylivingston/pen/JXqKWv

**Comment by Lotusvball** [comment]
Same here

**Comment by agentirons** [comment]
Yahoo Weather API is down, see here: https://developer.yahoo.com/weather/

**Comment by agentirons** [comment]
Probably related to this issue: https://github.com/monkeecreate/jquery.simpleWeather/issues/221

You can see at this link there's some sort of OAuth problem: http://weather.yahooapis.com/forecastrss

**Comment by perryodical** [comment]
thank you @agentirons. Using this for an internal interview tomorrow so at least I know the issue, can create some demo code and talk around it if need be.

**Comment by fleeting** [comment]
It looks to be working again. Yahoo's API was down for a little bit.
