### ISSUE TITLE
Wind Speed Inaccurate 

### ISSUE THREAD

**Issue by MikeChipshop** [monkeecreate/jquery.simpleWeather#242]
Afternoon all!

After the headache of Yahoo messing around with Oauth, everything 'appears' to be back to normal, except with one odd issue. My wind speed is incorrect, like very incorrect.

For example, today it's returning 28.97, while the actual Yahoo weather website is showing 11.

Is any one else getting this? It's complete feasable i'm cocking something up though ;)
Site for reference is https://midgr.uk

On a side note, love the script. Any chance of moving to the Dark Sky API... it's much more accurate (well, for me!).

**Comment by B-Roc** [comment]
I am having the same wind speed issue. I wonder if it is pushing the wind "gust" speed and not average speed? Either way, it isn't accurate when compared to Yahoo weather website.
