### ISSUE TITLE
please give idea how to get this seperately

### ISSUE THREAD

**Issue by libinantoecrubit** [monkeecreate/jquery.simpleWeather#247]
i need current time of the city i given ( time only independently )
and day in full text (like tuesday) can you tell the param

**Comment by fleeting** [comment]
simpleWeather doesn't have anything to give you the current time - only time it has is the time the weather data was last updated with `weather.updated`. You could try using [moment.js](http://momentjs.com/) and [moment timezone](http://momentjs.com/timezone/) to get current time in the timezone you are looking for. I would also recommend searching [stackoverflow](http://stackoverflow.com/) if you have problems.

**Comment by libinantoecrubit** [comment]
Thanks james for your reply
