### ISSUE TITLE
Auto Update for weather not working 

### ISSUE THREAD

**Issue by asoomar** [monkeecreate/jquery.simpleWeather#249]
I have tried to get the weather to auto update on a page that is constantly open, but it does not work. The code below is what I have. Can someone please let me know what is wrong or what I should change?

 `if ("geolocation" in navigator) {
    navigator.geolocation.getCurrentPosition(function (position) {
        loadWeather(position.coords.latitude + ',' + position.coords.longitude);
    });
} else{
    loadWeather('Austin, TX', '' );
}

$(document).ready(function() {
    setInterval(loadWeather, 10000);
});

function loadWeather(location, woeid){
    $.simpleWeather({
    location: location,
        woeid: woeid,
        unit: 'f',
        success: function(weather){
            city = weather.city;
            temp = weather.temp+'&deg;';
            wcode = '<img class="weathericon" src= "images/weathericons/' + weather.code + '.svg">';
            wind = '<p>' + weather.wind.speed + '</p><p>' + weather.units.speed + '</p>';
            humidity = weather.humidity + ' %';
            highlow = '&uarr; ' + weather.high + '&deg  ' + '&darr; ' + weather.low + '&deg';
            current = weather.currently;
            heatindexwindchill = '<img src= "http://www.weatherjon.org/meteo/homepage/blocks/radarUS/icons/dark/heatIndex.png" style="width:25px;height:25px;">' + ' ' + weather.heatindex + '&deg;    ' + '<img src= "http://pngimg.com/upload/snowflakes_PNG7576.png" style="width:25px;height:25px;">' + ' ' + weather.wind.chill + '&deg;';
            
            
            dateone = weather.forecast[1].day;
            forecasticonone = '<img class="forecasticoneone" src= "images/weathericons/' + weather.forecast[1].code + '.svg">'
            forecastone = weather.forecast[1].text ;
            highone = '&uarr; ' + weather.forecast[1].high+ '&deg';
            lowone = '&darr; ' + weather.forecast[1].low+ '&deg';
            
            
            datetwo = weather.forecast[2].day;
            forecasticontwo = '<img class="forecasticoneone" src= "images/weathericons/' + weather.forecast[2].code + '.svg">'
            forecasttwo = weather.forecast[2].text ;
            hightwo = '&uarr; ' + weather.forecast[2].high+ '&deg';
            lowtwo = '&darr; ' + weather.forecast[2].low+ '&deg';
            
            
            datethree = weather.forecast[3].day;
            forecasticonthree = '<img class="forecasticoneone" src= "images/weathericons/' + weather.forecast[3].code + '.svg">'
            forecastthree = weather.forecast[3].text ;
            highthree = '&uarr; ' + weather.forecast[3].high+ '&deg';
            lowthree = '&darr; ' + weather.forecast[3].low+ '&deg';
            
            
            datefour = weather.forecast[4].day;
            forecasticonfour = '<img class="forecasticoneone" src= "images/weathericons/' + weather.forecast[4].code + '.svg">'
            forecastfour = weather.forecast[4].text ;
            highfour = '&uarr; ' + weather.forecast[4].high+ '&deg';
            lowfour = '&darr; ' + weather.forecast[4].low+ '&deg';
            
            lastupdated = 'Last updated on ' + weather.updated;
            
            $(".location").text(city);
            $(".temperature").html(temp);
            $(".climate_bg").html(wcode);
            $(".windspeed").html(wind);
            $(".humidity").text(humidity);
            $(".highlowtemp").html(highlow);
            $(".condition").text(current);
            $(".heatwind").html(heatindexwindchill);
            
            $(".dateone").html(dateone);
            $(".forecasticonone").html(forecasticonone);
            $(".forecastone").html(forecastone);
            $(".highone").html(highone);
            $(".lowone").html(lowone);
            
            $(".datetwo").html(datetwo);
            $(".forecasticontwo").html(forecasticontwo);
            $(".forecasttwo").html(forecasttwo);
            $(".hightwo").html(hightwo);
            $(".lowtwo").html(lowtwo);
            
            $(".datethree").html(datethree);
            $(".forecasticonthree").html(forecasticonthree);
            $(".forecastthree").html(forecastthree);
            $(".highthree").html(highthree);
            $(".lowthree").html(lowthree);
            
            $(".datefour").html(datefour);
            $(".forecasticonfour").html(forecasticonfour);
            $(".forecastfour").html(forecastfour);
            $(".highfour").html(highfour);
            $(".lowfour").html(lowfour);
            
            $(".lastupdated").html(lastupdated);
        },
        
        error: function(error) {
            $("error").html('<p>' + error + '</p>');
        }
    });
}`

**Comment by fleeting** [comment]
Your `setInterval(loadWeather, 10000);` is calling `loadWeather` which is looking for two params - location, woeid. That will need to be something like `setInterval(loadWeather('Austin, Texas', ''), 10000);`.

Also, it could be helpful to put that in a codepen or jsfiddle in the future so we can see and modify the code as needed. Here is the original auto update demo http://codepen.io/fleeting/pen/mdwlI.
