### ISSUE TITLE
Geolocation demo - No error message shown

### ISSUE THREAD

**Issue by jcortes0309** [monkeecreate/jquery.simpleWeather#252]
Hi:

No error message is shown when denying the request from the browser to access my location while using the geolocation demo (http://codepen.io/fleeting/pen/Idsaj).  I also tried changing the code on my codepen example (using jquery.simpleWeather), but it seems the error: function(error) is not being triggered.

Regards,
Juan A.

**Comment by chougule-ashwini** [comment]
Hi,

I too have same issue. Can you please tell me reason?

**Comment by fleeting** [comment]
That was just a quick demo on geolocation, it's not accounting for if a user denies access. I would check out https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation if you need more details on using geolocation.
