### ISSUE TITLE
Sunset and sunrise information formatted incorrectly

### ISSUE THREAD

**Issue by jcortes0309** [monkeecreate/jquery.simpleWeather#253]
The formatting of the sunrise / sunset shows incorrectly.  Instead of showing the time as 7:03 PM, it is showing it as 7:3 pm.  I have attached a Word document that shows the issue.

[Codepen_sunrise_sunset_display.docx](https://github.com/monkeecreate/jquery.simpleWeather/files/384625/Codepen_sunrise_sunset_display.docx)

**Comment by fleeting** [comment]
Yeah, this is a known issue with Yahoo's API. It seems to strip out the zero. This would be something they have to fix.

**Comment by jcortes0309** [comment]
Great, thanks a lot for the information and the quick reply.

**Comment by fleeting** [comment]
No problem. It's a bummer to have the issue and one day I'll get around to replacing Yahoo's API with a better one. Since the zero that gets removed can be the first or second digit, it's not really possible for me to just add a zero to it either.

**Comment by jcortes0309** [comment]
Gotcha!  That's really weird that it will remove the zero regardless of the location.  I'm just learning programming myself so don't know what could be a better option, but found the jquery.simpleWeather very easy to use.  I'm following the FreeCodeCamp curriculum so I have to create a Local Weather App (https://codepen.io/jcortes0309/pen/ZOxqmq)
