### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by karina-acs-web** [monkeecreate/jquery.simpleWeather#254]
![weather-wdget-down](https://cloud.githubusercontent.com/assets/7376424/17155426/04caa566-5353-11e6-945a-1cff3c279488.png)

I get a console error:
Failed to load resource: the server responded with a status of 404 () https://l.yimg.com/a/i/us/nws/weather/gr/30d.png
and
https://l.yimg.com/a/i/us/nws/weather/gr/34d.png

**Comment by fleeting** [comment]
I'm not sure where those image urls are coming from. The current urls look like https://s.yimg.com/zz/combo?a/i/us/nws/weather/gr/30d.png. Make sure you are using the current version of simpleWeather.
