### ISSUE TITLE
Wind.chill information doesn't change to C

### ISSUE THREAD

**Issue by jcortes0309** [monkeecreate/jquery.simpleWeather#255]
I created a test app that shows the current weather in F or C (based on what option is chosen), but when changing from F to C, the wind.chill information doesn't change to the actual C temperature.  See attachment for more information.

[Codepen_F_to_C_change.docx](https://github.com/monkeecreate/jquery.simpleWeather/files/384959/Codepen_F_to_C_change.docx)

**Comment by jacob-on-github** [comment]
Here is the original [Pen](http://codepen.io/jcortes0309/pen/ZOxqmq) if anyone wants to look at it.
