### ISSUE TITLE
Trailing zeros on Sunrise/Sunset.

### ISSUE THREAD

**Issue by stevehjohn** [monkeecreate/jquery.simpleWeather#256]
Hi,

Great plugin, thanks for sharing. Just noticed an issue whereby the sunset is displaying as (e.g.) 9:1 pm.
Does this mean 9:01pm or 9:10pm?

Thanks,

Steve.

**Comment by stevehjohn** [comment]
If it helps:

        function formatTime(time) {
            var hour = time.substr(0, time.indexOf(':'));
            var minutes = time.substr(time.indexOf(':') + 1);
            minutes = minutes.substr(0, minutes.indexOf(' '));
            if (minutes.length < 2) {
                minutes = "0" + minutes;
            }
            var period = time.substr(time.indexOf(" ") + 1);
            return hour + ":" + minutes + " " + period.toUpperCase();
        }

**Comment by fleeting** [comment]
Yeah, it's a known issue with Yahoo's API that seems to be stripping the zero in some cases on sunrise and sunset values.
