### ISSUE TITLE
Possible solution for translations

### ISSUE THREAD

**Issue by fatpixelstudio** [monkeecreate/jquery.simpleWeather#257]
Hi, 

In a recent project I've used this sweet plugin. Great work! 

I needed the weather status in a different language then the Yahoo API provides. This is not supported (as stated in the docs). The solution I used to fix this, is to translate the status codes myself into my native language (Dutch), and save it in an object. This could probably also be a JSON file.

`var weatherstatus_nl = {
	0 : 'Tornado',
	1 : 'Tropische storm',
	2 : 'Orkaan',
	3 : 'Zware onweersbuien',
	4 : 'Onweersbuien',
	5 : 'Regen en sneeuw',
	6 : 'Regen en ijzel'
	// and so on...
};`

When displaying the status, I'm using the `weather.code` variable to get the corresponding status from the translation.

`html += '<p class="Weather-line Weather-line--current">'+weatherstatus_nl[weather.code]+'</p>';`

Maybe this helps others in using this plugin in their native language.

**Comment by fleeting** [comment]
Thanks for this. A few others have been doing translations the same way and I believe it's the best way to do it.
