### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by abruneau** [monkeecreate/jquery.simpleWeather#258]
Since a few hours I get this message

jquery.min.js:4 GET https://query.yahooapis.com/v1/public/yql?format=json&rnd=20168119&diagnost…eo.places(1)%20where%20text=%22Paris%22)%20and%20u=%22c%22&_=1473095163744 net::ERR_CONNECTION_REFUSED

{"error":{"lang":"en-US","description":"You must specify a yql statement (q=) to execute"}}

**Comment by fleeting** [comment]
I'm not currently getting any errors on the demos or other sites using it. I would need to see the code you are using to call simpleWeather or a link to where the error is happening.

**Comment by abruneau** [comment]
It work again with no change in my code. Maybe it was a Yahoo bug.

Thank you for your quick response
