### ISSUE TITLE
Forecast Question

### ISSUE THREAD

**Issue by alexwel** [monkeecreate/jquery.simpleWeather#259]
Hi, First of great script. 
Question, is there any way to limit the forecast on how many days to show? and not show all 10 days.

**Comment by fleeting** [comment]
Yep, you can change `for(var i=0;i<weather.forecast.length;i++) {` to something like `for(var i=0;i<3;i++) {` to only show three days. A quick note on this is that if the API returns less than the number of days you put (ex: if you put 6 but the api for some reason returns 5) it would error out. In most cases you should be good but you can always add a check to make sure the `weather.forecast.length` is `<=` whatever number you put.

**Comment by alexwel** [comment]
Thanks just what I need
