### ISSUE TITLE
Morning, midday and night

### ISSUE THREAD

**Issue by holhel11** [monkeecreate/jquery.simpleWeather#261]
I need to display the weather like this image:

![14599733_10157505120220257_1212782888_o](https://cloud.githubusercontent.com/assets/1552433/19106462/be963386-8ae7-11e6-82a2-088ddab1270f.jpg)

I noticed Yahoo displays the weather each hour. Is it possible to do with this plugin?

Thanks

**Comment by fleeting** [comment]
Currently not possible with simpleWeather. Yahoo only returns data for the day as a whole. There are some other APIs that return hourly info like the NOAA and Weather.com feeds.
