### ISSUE TITLE
weather widget showing errors after load frequently

### ISSUE THREAD

**Issue by michael72653** [monkeecreate/jquery.simpleWeather#262]
I know there might be some change to Yahoo! 's side, but there are a lot of issues with the query not working after loading the page. Sometimes it won't load, then other times it will work. 

is there a way to look into the fix for this?

**Comment by joecacti** [comment]
I'm also seeing this issue.  I can't get it to show at all now.

**Comment by joelkienitz** [comment]
+1 on this issue. Also getting an error message: "There was a problem retrieving the latest weather information."

**Comment by joecacti** [comment]
Working now for me.

**Comment by jacob-on-github** [comment]
I have a Pen on CodePen using this plugin - it has been working.

**Comment by alexwel** [comment]
Having sambe problem time to time it gives me the error message: "There was a problem retrieving the latest weather information."

**Comment by lsterling03** [comment]
Same. It's been happening intermittently (but often) over the past several weeks. What can we do?

**Comment by fleeting** [comment]
The best alternative if Yahoo is proving too unstable is to use another weather API like https://darksky.net/dev/docs or https://openweathermap.org/api. Both require creating an account and using an API key which is why simpleWeather has never switched.
