### ISSUE TITLE
Using npm and SimpleWeather cdnjs together and get an error in console that jQuery is not defined in SimpleWeather

### ISSUE THREAD

**Issue by interglobalmedia** [monkeecreate/jquery.simpleWeather#263]
Hi,

I'm using npm for my project workflows and added the SimpleWeather cdnjs to my index.html because I didn't want to use bower. I use the jquery npm package to load my jquery. It works for my native JS that I created, but not for SimpleWeather. So my JS for SimpleWeather is not loading. Is there a way to fix this? Or, if using bower is the only way, can I somehow import SimpleWeather into npm package.json and js modules from bower? Thanks! This is the error I am getting in the console:

Uncaught ReferenceError: jQuery is not defined      jquery.simpleWeather.min.js:2

**Comment by fleeting** [comment]
It just sounds like you are including the simpleWeather.js before jQuery is loaded. The `<script>` for simpleWeather should be after jQuery. As for wanting to use `npm` to pull it, you can do `npm install --save-dev monkeecreate/jquery.simpleWeather`.

**Comment by interglobalmedia** [comment]
Thanks James! I'll try it out. I thought it might be that, but I was wondering why because I didn't think that I was calling jquery afterwards. But I'll figure it out. Thank you! I love Simple Weather.

**Comment by fleeting** [comment]
Let me know if you still have problems. It would also help to see the html where you are including simpleWeather, jQuery, and your main js stuff. However, if you are using gulp/grunt/etc to compile assets, it's just as easy to use npm to install simpleWeather and compile it with the others (just after jQuery) vs using the cdn.

**Comment by interglobalmedia** [comment]
James, the issue is that I am upgrading my project with new workflows and task runner etc. using npm. Previously, all I did was add scripts for jquery and SimpleWeather API cnjs at the bottom of my index.html file. Then it worked fine (except for time issues related to the icons which actually only started happening long after, but it's too early to even discuss that). Now, however, since I am modularizing my code with ES6 features and importing everything into my app.js folder (including the jquery which is called at the top of the app.js file), I no longer should have to add the jquery script in the index.html. And I am not. I tried to add a simpleWeather.js file to my modules folder in my scripts folder and then import it into my app.js file, but there is no named function or class to import from simpleWeather.js as wrapped in a closured anonymous function. That's where I got stuck, and that's where purportedly $ is not defined according to the Google Chrome JS console in Developer Tools. Does that make sense? I haven't pushed this yet to my repo here because it is not finished or working yet. You can take a look at my original code here before I made the changes but I don;t think that would be of any help to the current situation. However, I do have basically the same workflow setup in another project that you can use as a reference if you like: https://github.com/interglobalmedia/travel-agency-site

**Comment by interglobalmedia** [comment]
I tried everything re installing via npm install monkeecreate/jquery.simpleWeather --save-dev (meaning I removed my two js files related to it), and I still was unable to install. Of course my repo is called simpleweather. Maybe that is the issue?

**Comment by fleeting** [comment]
Sorry but without seeing the code I'm not able to help much. All I can say is the error seems to suggest that jQuery wasn't loaded before simpleWeather. If you are able to push up the code in a dev branch or even create a https://gist.github.com of the files, I can dig in a little more.

**Comment by interglobalmedia** [comment]
Good Idea. I have this in a separate features branch and will push it and then share the link here. Why didn't I think of that? Thanks!

**Comment by interglobalmedia** [comment]
James, here is the link to the es6-features branch with the structure and code you wanted to take a look at. It's still a "rough draft", but you will get the idea. Thanks! https://github.com/interglobalmedia/simpleweather/tree/es6-features

**Comment by fleeting** [comment]
Ahh, you are using webpack. I'm not really sure how that process works to make the jQuery import available to the other imports. It looks like the problem is with the webpack setup vs simpleWeather though as it works fine outside it. I would suggest hitting up StackOverflow to get help from those who know more about that.

**Comment by interglobalmedia** [comment]
Makes sense. I'll reach out there. Thanks for all your time! I'll let you know if I find a solution.

**Comment by interglobalmedia** [comment]
Hi James: I finally figured out how to resolve my jquery plugin issue with my Gulp workflow. It wasn't a webpack issue, it was as you and I had suspected initially, a jquery load issue. Here is the link to the gh-pages for the project: [](https://interglobalmedia.github.io/simpleweather)/ I thought you might be interested in seeing what I did. Thanks for this great plugin!
