### ISSUE TITLE
DIsplay in full the day of the week

### ISSUE THREAD

**Issue by shawnlow7** [monkeecreate/jquery.simpleWeather#264]
Hi,

Wanted to ask if there is a way to display the full day of the week for the forecast. Currently they are only showing as **Mon, Tue** etc.. what code should I include so that they are displayed as **Monday, Tuesday** etc.. Do I need to put an array somewhere for this to work?

Can you please help me out on this?

**Comment by fleeting** [comment]
Yeah, Yahoo only returns the abbreviated versions. You would just need to do an array using the abbreviated text as keys and the full text that you want as the values.

**Comment by shawnlow7** [comment]
Can you elaborate on this and maybe show me an example since I started learning JavaScript just a few weeks ago.
