### ISSUE TITLE
Wrong icon

### ISSUE THREAD

**Issue by charlesravndal** [monkeecreate/jquery.simpleWeather#267]
Hi! This is a wonderful plugin with full of possibilities!

Anyway, I get this wrong weather.code. For example it's morning in the location I specified and I get a night icon. I get code 33 (Clear sky night) instead of code 32 (sunny). When I checked Yahoo it displays code 32. I think there's something to do with time or something?

Also, is it possible for simpleWeather to use this API? http://www.yr.no/place/Norway/Oslo/Oslo/Oslo/data.html

**Comment by fleeting** [comment]
I would need to see the location you are using or a link to where it is at. Honestly though, simpleWeather just returns the code from Yahoo's API. I don't do anything to alter it and don't cache it. The API data will sometimes differ from the Yahoo Weather site though. If the data returned is wrong, it would just be what Yahoo gave me.

**Comment by charlesravndal** [comment]
Thanks for the fast reply! Here is the link: http://bt.kreateam.io/demo/weather/

I think there is something to do with time since it shifts to the correct icon and bg when it's nearing noon :)

**Comment by fleeting** [comment]
Ahh, you are using the demo css I had. There is a bug on it where I'm using `text-transform: uppercase;` on `#weather`. This is causing the weather icon font to convert `a` which is party cloudy night to `A` which is party cloudy day. If you add `text-transform: none;` to `#weather h1` in the css, it should fix it.

simpleWeather itself is working as expected, the demo was just quick and I didn't account for day/night icons when I did the text transform.

**Comment by charlesravndal** [comment]
Thank you :)
