### ISSUE TITLE
weather is down

### ISSUE THREAD

**Issue by textcursor** [monkeecreate/jquery.simpleWeather#268]
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[Learn More]jquery.min.js:1

^console is showing me that and weather is not loading on my page.

**Comment by chcreative** [comment]
It's not working for me either. Anyone else having issues?

**Comment by nicoool** [comment]
Mine is not working, just shows the loading screen.  I'm pretty sure everyone's isn't working since all of the demos on the main site are down.

**Comment by fleeting** [comment]
Correct, looks like Yahoo's API is currently down. See https://developer.yahoo.com/weather/.

**Comment by sams6** [comment]
So is someone looking into fixing it? What can be done now? Please suggest.

**Comment by fleeting** [comment]
I would assume Yahoo is working on getting it back up as most of their API feeds are down right now. I'm not associated with Yahoo, so that's as much info as I would have. Nothing can be done about it on my end.

**Comment by sams6** [comment]
ok, thank you for the update.

**Comment by sams6** [comment]
Its up again looks like

**Comment by ukeboyska** [comment]
down again.

**Comment by sid606** [comment]
Still down. But the strange thing is that one minute is up and the other is down. I read that we need to add power by yahoo so the API to work?
