### ISSUE TITLE
weather API is broken

### ISSUE THREAD

**Issue by sams6** [monkeecreate/jquery.simpleWeather#269]
Hi, This API is broken since morning. Not getting weather code, temperature and icons. 
![yahoo-weather-broken](https://cloud.githubusercontent.com/assets/9422004/20318711/4eab904e-ab39-11e6-9af0-4249f0ff7e31.JPG)

Please look into this, one of my application is entirely dependent on this.

**Comment by fleeting** [comment]
Duplicate of #268.
