### ISSUE TITLE
Changing hour format

### ISSUE THREAD

**Issue by dsa89** [monkeecreate/jquery.simpleWeather#270]
I'm trying to display to the sunset/sunrise parameters into the 24-hour format instead of the standard 12-hour variation. I want to know is it possible to change it through Simple Weather or is it entirely controlled by Yahoo?

**Comment by fleeting** [comment]
The date is whatever Yahoo returns. You should be able change the format using http://momentjs.com/ though.

**Comment by dsa89** [comment]
I'm still learning about JavaScript, so I don't have much of an idea on how to change it.
