### ISSUE TITLE
Geolocation not working

### ISSUE THREAD

**Issue by Savvant** [monkeecreate/jquery.simpleWeather#272]
Hi all, I developed a mobile app that uses a lot of geolocation functionality through the simple weather plugin. It worked well for a couple of weeks and then suddenly stopped showing any results (blank where the text used to be) even though I didn't change any of the code that worked initially. 

I think the issue is that the geolocation stopped working. Because it is not working on the geolocation demo on the simple weather site. 

Here is a segment of my code that used to work to automatically retrieve current weather conditions: 

/* Where in the world are you? */
$(document).ready(function() {
  navigator.geolocation.getCurrentPosition(function(position) {
    loadWeather3(position.coords.latitude+','+position.coords.longitude); //load weather using your lat/lng coordinates
  });
});

function loadWeather3(location, woeid) {
  $.simpleWeather({
    location: location,
    woeid: woeid,
    unit: 'c',
    success: function(weather) {
      html = '<p>'+weather.currently+'</p>';  
      
      $("#weather3").html(html);
    },
    error: function(error) {
      $("#weather3").html('<p>'+error+'</p>');
    }
  });
}

Thanks in advance!

**Comment by fleeting** [comment]
I'm honestly not sure on this. The geolocation on the demo does work over `https` (https://codepen.io/fleeting/pen/Idsaj). The current link doesn't work as it links to `http` and an update awhile back in some browsers require geolocation to be used over `https` (see https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins). 

I'll update the link to the demo to force `https`.
