### ISSUE TITLE
Indicating sunrise/sunset by using styling.

### ISSUE THREAD

**Issue by dsa89** [monkeecreate/jquery.simpleWeather#274]
I saw the example of indicating [temperature changes](http://codepen.io/fleeting/pen/wzvAE) by using different colors. I want to know if it's possible to do so by sun positions as well. If so, should the example shown in codepen would suffice or would a different code have to be used.

**Comment by fleeting** [comment]
It's possible but you would have to come up with the code/logic for determining the position of the sun based on sunrise/sunset and current time. `simpleWeather` it self doesn't do sun position but I would think it would be that difficult.
