### ISSUE TITLE
Data shown does not correlate with Yahoo website?

### ISSUE THREAD

**Issue by AlcuinGuest** [monkeecreate/jquery.simpleWeather#275]
Using simpleweather seems to be working fine, and I can display the weather in c/f for multiple locations. However, when i check the Yahoo weather site for that location, it is wildly different from the data just displayed by simpleweather. Not a problem with converting c/f because the numbers i am getting are similar, not a clear unit error.

What is going on here?

Anyone else having this problem?

**Comment by AlcuinGuest** [comment]
For example, I will get simpleweather to display the temperature in Bali and it will be 26deg, then i check on the Yahoo weather page for Bali and it will be 19deg. Etc etc.

**Comment by fleeting** [comment]
Odds are it's just a different set of weather data they are using between the site and API. I don't believe they use their own API for their weather stuff. You can also check the data being returned at https://developer.yahoo.com/weather/. `simpleWeather` doesn't really modify any of the data outside of converting temps if needed.

**Comment by AlcuinGuest** [comment]
Ah okay, thanks. Does returning the simple temperature return the high for the day, or the current temperature?

**Comment by fleeting** [comment]
`temp` will be the current temperature. Anything from `forecast` will be high/low. Full data listing on http://simpleweatherjs.com/.
