### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by BjarkeRJensen** [monkeecreate/jquery.simpleWeather#276]
I would like to use this great API in my project, but when browsing your demo's on CodePen i occasionally get a "Connection Failed" error to the Yahoo API. It seems a bit unstable. Am i the only one getting these errors ?

**Comment by nadsrosun** [comment]
Same issue since last week  :  'There was a problem retrieving the latest weather information'. Yahoo weather API not stable ?

**Comment by fleeting** [comment]
Yahoo's API has been pretty unstable. Their developer console was also throwing errors for most of today but everything seems to be back up now. The console is located at https://developer.yahoo.com/weather/ and is always worth checking there if it seems down.

**Comment by lsterling03** [comment]
Happening to me too. Often.

**Comment by dghez** [comment]
Happening a lot to me too.

**Comment by fleeting** [comment]
The best alternative if Yahoo is proving too unstable is to use another weather API like https://darksky.net/dev/docs or https://openweathermap.org/api. Both require creating an account and using an API key which is why simpleWeather has never switched.
