### ISSUE TITLE
How do i insert the code into my html webpage?

### ISSUE THREAD

**Issue by elliottolver** [monkeecreate/jquery.simpleWeather#277]
Is there a tutorial as to how to insert the app into my html page?

Ive tried to copy the content after downloading the app into my websites html and css but its not appearing.

I'm really not sure how to do it any advise would be appreciated.

thanks

**Comment by fleeting** [comment]
I'm not really sure what you're looking for here. You need to include jQuery, simpleWeather and then init it with your options (refer to one of the demos as an example). Also, Yahoo's API was down earlier today so it's possible it wasn't working from that.
