### ISSUE TITLE
this plugin doesn't work anymore

### ISSUE THREAD

**Issue by gondo** [monkeecreate/jquery.simpleWeather#278]
reason: `geo.placefinder table is no longer supported`
full error: `/**/callback5156091({"query":{"count":0,"created":"2016-12-29T00:10:04Z","lang":"en-US","diagnostics":{"publiclyCallable":"true","javascript":{"execution-start-time":"0","execution-stop-time":"2","execution-time":"1","instructions-used":"0","table-name":"geo.placefinder"},"user-time":"2","service-time":"0","build-version":"2.0.84"},"meta":{"message":"geo.placefinder table is no longer supported"},"results":null}});`

**Comment by fleeting** [comment]
I dropped `geo.placefinder` back in January (https://github.com/monkeecreate/jquery.simpleWeather/commit/59e0ce55a397c72b4aa26805a849d93380b5c38e). You'll need to update to `3.1.0`.
