### ISSUE TITLE
Get "There was a problem retrieving the latest weather information" error 75% of the time.

### ISSUE THREAD

**Issue by m-pcwebdeveloper** [monkeecreate/jquery.simpleWeather#280]
Using version 3.10 get the subject error quite often. Here is my code:
$(document).ready(function() 
 	{
	 	if($('#golf').length)
	 	{
	  		$.simpleWeather(
	  		{
	    		location: 'Spencerport, ny',
	    		unit: 'f',
	    		success: function(weather) 
	    		{
	    			html = '<p>Current Conditions:&nbsp;';
	      			html += weather.temp+'&deg;'+weather.units.temp;
	      			html += '&nbsp;'+ weather.currently+'</p>'
	//      			html += '<ul><li>'+weather.city+', '+weather.region+'</li>';
	//      			html += '<li class="currently">'+weather.currently+'</li>';
	//      			html += '<ul>';
	//      		html += '<li>'+weather.alt.temp+'&deg;C</li></ul>';
	  
	      			$("#weather").html(html);
	    		},
	    		error: function(error) 
	    		{
	      			$("#weather").html('<p>'+error+'</p>');
	    		}
	  		});
	  	}
 	});

**Comment by fleeting** [comment]
Yeah, the Yahoo Weather API is pretty unstable now days. See #276 for alternative weather sources.
