### ISSUE TITLE
Current Status of simpleWeather

### ISSUE THREAD

**Issue by fleeting** [monkeecreate/jquery.simpleWeather#281]
As many have noticed over the last several months, the Yahoo Weather API has been extremely unstable. With the state of Yahoo as a company, it's unlikely their weather API will ever become stable again. Most stable and feature rich weather APIs like https://openweathermap.org/api and https://darksky.net/dev/ require API keys and have pricing options which is outside the scope of this project for now.

If I get some time moving forward I'll look at the other API options. I recommend using one of the above APIs instead and hopefully I'll get an updated version of simpleWeather at some point or kill the project.

**Comment by ukeboyska** [comment]
thanks for the update! i'm just curious - what's the issue right now? the yahoo API seems to be up consistently (https://developer.yahoo.com/weather/) but weather only comes up in SW demos the first time i load them, then very intermittently (if at all). i see this console log: "Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings." ... i took a look and it seems there's now API keys for yahoo weather API...maybe that's the issue?

**Comment by fleeting** [comment]
They did add oAuth stuff to several APIs awhile back but the weather one has worked without it, I'm sure it's the cause of some issues but the API in general is down pretty often. I pretty constantly get `results: null` on https://developer.yahoo.com/weather/ (did just now actually).

**Comment by ukeboyska** [comment]
yeah. so frustrating.

**Comment by qroft** [comment]
Marissa Meyer just left Yahoo and the company changed their registration name to something weird.
For me these are signs that some marketeers are changing the direction of the company and soon will get to free-services like the weather api and set up some fees - imho.

**Comment by steved1982** [comment]
I am seeing the same from the Yahoo API, my feeds just say error loading the channel all the time

**Comment by pmarkoulidakis** [comment]
They now ask for an oauth token https://developer.yahoo.com/weather/

**Comment by fleeting** [comment]
@pmarkoulidakis Yeah, they started that sometime last year but the stability is still an issue even when using OAuth.

**Comment by jcorbett123** [comment]
Any chance you could show, those of us who have oauth keys, how to pass that along in simpleweather? I hate to see this project stop because of Yahoo. I would really appreciate it and I'm sure others would too. I know passing the key and secret along in our codes is risky, but some of us use it for personal or intranet purposes.

**Comment by pmarkoulidakis** [comment]
I found this on SO. I havent give a try yet. 
http://stackoverflow.com/questions/36186538/making-yahoo-weather-api-request-with-oauth-1

**Comment by interglobalmedia** [comment]
Hi @fleeting ,

I checked out my simpleweather app the other day in Firefox (and again today) as well as Safari (today), and both ask permission to access location. After I hit share location, the app immediately displayed the weather. HOWEVER, with Chrome, it NEVER asks permission to access your location. That is why such a lag (it's guessing), and sometimes undefined or nothing pops up. I am investigating this further to see whether or not there is a hack for this in Chrome and will get back to you. So I wonder which browser people who complained about the app were using, and were they asked to share their location?  Best regards, Maria

**Comment by hsoj95** [comment]
This might turn out to be an unpopular idea, but have you thought about trying to "Web Scrape" to get weather info you need? I know you can do it in PHP and Node.JS, but I don't actually know if it's achievable in plain JS/jQuery. I know at a small scale it's basically ok, but you'd have to be the judge of what constitutes an "acceptable" number of people using your platform to web scrape a site. It would possibly make an easy way to obtain weather data without needing an API, if it could be achieved to begin with and was ethical.

**Comment by BandonRandon** [comment]
Hi @interglobalmedia not sure if you're still having trouble with chrome but I did some digging and found that currently there's no timeout or error response in the sample code. I have updated the sample code here to add an error and success callback. This dosen't solve the problem in Chrome but at least gives the user a helpful answer. 

Updated example:https://codepen.io/anon/pen/jGePvN
Helpful resources:
https://developers.google.com/web/fundamentals/native-hardware/user-location/
https://stackoverflow.com/a/3885172
Error codes: https://dev.w3.org/geo/api/spec-source.html#position_error_interface

**Comment by BrookeDot** [comment]
Hi @fleeting I just forked your project to create "simplerweather.js" using Dark Sky's API. It's not perfect and is somewhat tailored to my project but wanted to drop a note here in case you or others found it useful:
https://github.com/BrookeDot/SimplerWeather

**Comment by fleeting** [comment]
@BrookeDot Thanks for that! I'll add a link to it in the readme here shortly. I love Dark Sky's API, I just wish they allowed you to restrict your API key to specific domains so it wouldn't be such a security risk exposing your API key in javascript like that.

**Comment by BrookeDot** [comment]
> I love Dark Sky's API, I just wish they allowed you to restrict your API key to specific domains so it wouldn't be such a security risk exposing your API key in javascript like that.

Yeah that would be nice, my work-around was to create a server side proxy which can then be limited by domain. I used PHP but there's no reason why you couldn't use any server-side language or third-party hosting solution. 

The way the proxy works if you output the JSON in a file like this:
https://github.com/BrookeDot/SimplerWeather/blob/master/proxy.php

Then set the URL in options for `SimplerWeather.js` 
```
  authmethod: 'proxy',
  proxyurl: 'proxy.php',
```

Not perfect but at least better than an exposed API key :)
