### ISSUE TITLE
SimpleWeatherJS with GitHub pages

### ISSUE THREAD

**Issue by randomdude583** [monkeecreate/jquery.simpleWeather#282]
I am fairly new to using GitHub pages, and building websites in general, and i'm trying to figure out how to implement SimpleWeatherJS into my site. I'm using a Jekyll setup on GitHub, and any help would be very appreciated!

**Comment by fleeting** [comment]
Best bet would be to include simpleWeather using the cdn. Using it on GitHub Pages is no different than using it anywhere as it's just javascript. That said, the weather API is pretty unstable so if it's not working it could be due to the API.
