### ISSUE TITLE
Just Curious- How does this work? Am I still limited to Yahoo's 2,000 calls? Are you paying for all of our requests?

### ISSUE THREAD

**Issue by gkgkgkgk** [monkeecreate/jquery.simpleWeather#283]
Im using darksky now, and asking my (two) users to get their own keys. It is a casual project, non-commercial (yet). I have heard simpleWeather.JS may be going offline... should I change to it? How does it work, too?
Thanks.

**Comment by justinwhall** [comment]
No API key require [example](https://query.yahooapis.com/v1/public/yql?format=json&rnd=20171320&diagnostics=true&q=select%20*%20from%20weather.forecast%20where%20woeid=2490551%20and%20u=%22f%22).

Appears the API is not stable. Sad as other options require an API key.

**Comment by fleeting** [comment]
If you are already using DarkSky's API now, I would stick with it.
