### ISSUE TITLE
changing wind speed to KPH & display

### ISSUE THREAD

**Issue by satain41** [monkeecreate/jquery.simpleWeather#285]
Hi there,

Just trying to wrap my head around the .js, as on the demo http://codepen.io/fleeting/pen/xklfq, so i can suit to what i need before i can proceed with anything. My location is ;Gibraltar, GI', and unit: 'd', to show degrees celsius, but i also require to show wind speed by kph, would anybody be able to show me the line of code as to how to change the demo js to show kph wind speed from yahoo weather & the units KPH ?

Many thanks

**Comment by BandonRandon** [comment]
Hi there, 

To show `kph` you'll want to set the `unit` to `c`. Note from the Yahoo Weather API

> Note that the default RSS feed uses Fahrenheit degree units and English units for all other attributes (miles, pounds per square inch, miles per hour). If Celsius has been specified as the degree units for the feed (using the u request parameter), all the units are in metric format (Celsius, kilometers, millibars, kilometers per hour). 

Updated demo: https://codepen.io/anon/pen/jGLqZO

If you want to show the temperature in `F` but wind speed in `kph` use `alt.temp` and `alt.unit` when displaying the temperature.
