### ISSUE TITLE
google maps not working when I use simple weather

### ISSUE THREAD

**Issue by PavanKallur** [monkeecreate/jquery.simpleWeather#286]
Hi,

I am facing problem in using google maps and simpleweather both on same page.

I wanted to get map along the weather of city for some hotel website.

I have functions defined as follow:

        function initWeatherWidget(hotelLocation, hotelWoeid) {
            // var weatherElement = $('#weatherWidgetContainer');
            $.simpleWeather({
                location: hotelLocation,
                woeid: hotelWoeid,
                unit: 'c',
                success: function(weather){
                    city = weather.city;
                    temp = weather.temp + '&deg;';
                    wcode = '<img class="weathericon" src="css/images/weathericons/' + weather.code +'.svg">';
                    wind = '<p>' + weather.wind.speed + ' </p> <span> ' + weather.units.speed + '</span>';
                    humidity = weather.humidity + '%';
                    todayDay = weather.forecast[0].date + weather.forecast[0].day;
                    $(".location").text(city);
                    $(".temperature").html(temp);
                    $(".climate_bg").html(wcode);
                    $(".windspeed").html(wind);
                    $(".humidity").text(humidity);
                    $(".todayDay").text(todayDay);
                },
                error: function(error) {
                    $(".error").html('<p>' + error + '</p>');
                }
            })
        }

    function initLocationWidget() {
        var mapElement = $('#mapContainer'),
            hotelLatLng = { lat: mapElement.data('latitude'), lng: mapElement.data('longitude') },
            hotelMapOptions = {
                zoom: mapElement.data('zoom'),
                center: hotelLatLng,
                mapTypeControl: true,
                scrollwheel: false
            },
            hotelMap = new google.maps.Map(document.getElementById('mapContainer'), hotelMapOptions);
            hotelMarkerOptions = {
                position: hotelLatLng,
                map: hotelMap
            },

            hotelMarker = new google.maps.Marker(hotelMarkerOptions),
            content = "<div style='overflow: hidden; width:300px; height:80px; '><b>" + mapElement.data('hotelName') + "</b><br>" + mapElement.data('hotelAddress') + "<br>" + mapElement.data('hotelPhone') + "</div>",
            hotelTip = new google.maps.InfoWindow({
                maxWidth: 400,
                position: hotelLatLng,
                content: content
            });
            hotelTip.open(hotelMap);
        }

Call as follows:

            initWeatherWidget($('#weatherWidgetContainer').data('city'));
            initLocationWidget();

Kindly reply on this issue asap.

**Comment by fleeting** [comment]
What error are you getting? Does simpleWeather work without the map code? If you could create a CodePen or jsfiddle of what you are trying to do it would help.

**Comment by PavanKallur** [comment]
Hi,

Thank you for reply.

It was my mistake I used .location class to update city name, that
overridden map location class.

Thank you and Regards
Pavan Kallur
