### ISSUE TITLE
Request: all outputs of weather.text

### ISSUE THREAD

**Issue by chris-ackerman** [monkeecreate/jquery.simpleWeather#288]
I am making a website where part of the background changes based on the current weather conditions and the javascript I've written makes that decision based on the weather conditions. Is there anywhere I can find all of the possible outputs from calling weather.text so I can write my if statements correctly?

**Comment by fleeting** [comment]
These are all the condition codes - https://developer.yahoo.com/weather/documentation.html#codes.
