### ISSUE TITLE
It is possible to get Weather for Latitude Longitude?

### ISSUE THREAD

**Issue by onigetoc** [monkeecreate/jquery.simpleWeather#289]
It is possible to get Weather for Latitude Longitude?

I will use HTML5 geolocation to get Lat and Long and get the Weather.

**Comment by fleeting** [comment]
Yep, you can pass in a location including latitude/longitude. Demo is at https://codepen.io/fleeting/pen/Idsaj.

**Comment by onigetoc** [comment]
Yeah, i just did it true over https
https://codepen.io/onigetoc/pen/eWpQZW
