### ISSUE TITLE
Crazy forecast!

### ISSUE THREAD

**Issue by nettlebay** [monkeecreate/jquery.simpleWeather#290]
Hello,
Forecasts for St Martin (West Indies) or Anguilla are really crazy! For example, it shows 51 km / h wind speed while the NOAA indicates 24 km / h (15 Mph). Also, the indicated temperature is 1 to 3ºC below the true temperature. I believe the source is not good. Note that I use this API in _CNTP - Custom New Tab Page_.

**Comment by fleeting** [comment]
This would be an issue with Yahoo's API and their source data. I have no control over what is returned.

**Comment by nettlebay** [comment]
OK! I understand.
