### ISSUE TITLE
Simple Weather for Auto Generation

### ISSUE THREAD

**Issue by tweetoxygen** [monkeecreate/jquery.simpleWeather#294]
Hello,

I was going through the weather Plugin and I noticed something. You have to insert in your current location for you to be able to see the weather at that location. What if you want to make it show based on the current location of the person viewing your page? 
So if I am in Canada (for example), it shows me the weather report of Canada and if someone else tries to visit the same website from India (for example), it shows the weather report of India.
How can this be achieved please using this plugin?

Thanks.

**Comment by fleeting** [comment]
There is a demo on the website for using geolocation. https://codepen.io/fleeting/pen/Idsaj
