### ISSUE TITLE
detect auto location

### ISSUE THREAD

**Issue by MuhammadBilalMughal** [monkeecreate/jquery.simpleWeather#295]
how to detect auto location

**Comment by fleeting** [comment]
Geolocation demo is https://codepen.io/fleeting/pen/Idsaj?editors=0010. You can just remove it from being inside the click to have it run on page load. After it gets the location, you'll need to call simpleWeather to actually look up the data. More docs on using geolocation: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation.
