### ISSUE TITLE
Is this not working anymore?

### ISSUE THREAD

**Issue by seanvree** [monkeecreate/jquery.simpleWeather#296]
I keep getting this error in the browser:

```
jquery.simpleWeather.min.js:3 Uncaught TypeError: $.simpleWeather is not a function
    at HTMLDocument.<anonymous> (jquery.simpleWeather.min.js:3)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.K (jquery.min.js:2)
```

**Comment by BandonRandon** [comment]
I'm using the script without error on my site. If you're talking about the demos what looks like is going on is that GitHub is blocking hot linking to `https://cdn.rawgit.com/monkeecreate/jquery.simpleWeather/master/jquery.simpleWeather.min.js` so the SimpleWeather plugin isn't being loaded. 

Instead you can update the links (under Settings in CodePen) to use a working CDN URL for example:
`https://
cdnjs.cloudflare.com/ajax/libs/jquery.simpleWeather/3.1.0/jquery.simpleWeather.min.js`

Here's a new URL with the updated link for the basic demo:
https://codepen.io/anon/pen/dVzMzJ

If you're having trouble on a live site then please provide more details :)

**Comment by jacobherrington** [comment]
@seanvree I'm fairly certain it's not being supported anymore.

**Comment by BandonRandon** [comment]
#281 has an update on the project's current status. 

I took this question as "does it work" rather than "is it being maintained". The code is still working for me even with the latest jQuery version. It does currently rely on the Yahoo Weather API remaining live though.
