### ISSUE TITLE
Error Retrieving Weather Info

### ISSUE THREAD

**Issue by Spunz007** [monkeecreate/jquery.simpleWeather#301]
Hi,

I have been testing the weather widget for a week and has been fine but right now I have got this error appearing:

There was a problem retrieving the lastest weather information

Has something broken?
The weather region is: Auckland, NZ

Thanks

**Comment by fleeting** [comment]
See https://github.com/monkeecreate/jquery.simpleWeather/issues/308#issuecomment-451467660.
