### ISSUE TITLE
Is There a 'Feels Like' Temperature Available?

### ISSUE THREAD

**Issue by JoeJoomla** [monkeecreate/jquery.simpleWeather#304]
Thanks for your simpleWeather code. I really appreciate what you have done here.

I'm always being asked what the 'feels like' temperature is. Are any of the outputs on the [simpleWeather.dataDump.js [v3.1.0] Codepen](https://codepen.io/fleeting/pen/yjhBK) data dump associated with a 'feels like' temperature?

**Comment by fleeting** [comment]
Yeah, the `weather.heatindex`.
