### ISSUE TITLE
Problem Retrieving Current Weather today

### ISSUE THREAD

**Issue by Donn187** [monkeecreate/jquery.simpleWeather#305]
Hi,

Upon checking today there is an issue  shown:

THERE WAS A PROBLEM RETRIEVING THE LATEST WEATHER INFORMATION.

this is visible to our site and on the demo site below as well.
https://codepen.io/fleeting/pen/xklfq

**Comment by JoshuaKimsey** [comment]
It seems to be working now. My guess is it might have been an issue on Yahoo's end. (They are the one's who's api powers this plugin)
