### ISSUE TITLE
As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. 

### ISSUE THREAD

**Issue by s3bast** [monkeecreate/jquery.simpleWeather#308]
https://developer.yahoo.com/weather/?guccounter=1

Simple Weather do not work anymore.

**Comment by saurioo** [comment]
There is no way to update Simple Weather to the new api https://weather-ydn-yql.media.yahoo.com/forecastrss ?

**Comment by HHawk** [comment]
No more weather on my site......??!?!? :(
HELP!!

**Comment by joasag** [comment]
Having the same issue. Is there any chance this might be fixed?

**Comment by beavcast** [comment]
Same issue. Hope this could be fixed soon! Thanks

**Comment by haseebtirur** [comment]
Same issue.

**Comment by fleeting** [comment]
simpleWeather has been unreliable with the Yahoo API for some time and there are no plans to update it. There is a fork that uses a different API that might be worth a look for those needing it. https://github.com/BrookeDot/SimplerWeather

**Comment by aik1979** [comment]
I've used this as a temporary measure until we can find a solution

https://weatherwidget.io/
