### ISSUE TITLE
$.simpleWeather is not a function

### ISSUE THREAD

**Issue by agenciaRSE** [monkeecreate/jquery.simpleWeather#309]
Hi there! I have an issue on this site [http://urban.network] with the plugin, for some reason dont recognize the function <$.simpleWeather is not a function>, anyone knows what is causing this? Thanks for the awesome plugin and the help! 

jQuery.Deferred exception: $.simpleWeather is not a function @https://urban.network/show.php#:2101:3
j@https://code.jquery.com/jquery-3.2.1.min.js:2:29997
g/</k<@https://code.jquery.com/jquery-3.2.1.min.js:2:30313
 undefined jquery-3.2.1.min.js:2:31569
TypeError: $.simpleWeather is not a function[Conocer más] show.php:2101:3
<anónima>
https://urban.network/show.php#:2101:3
j
https://code.jquery.com/jquery-3.2.1.min.js:2:29997
g/</k<
https://code.jquery.com/jquery-3.2.1.min.js:2:30313

**Comment by fleeting** [comment]
See https://github.com/monkeecreate/jquery.simpleWeather/issues/308#issuecomment-451467660.
