### ISSUE TITLE
Initialize

### ISSUE THREAD

**Issue by northgunner** [monkeecreate/jquery.simpleWeather#75]
Hi there,

I am pretty new to jquery and js. I have been reading through one of the closed-issues and it is suggested the person needs to initialize simpleWeather on the page. However, I don't understand how that is done. Thanks

**Comment by legramo** [comment]
Hi, after several times trying to use your plugin, i always get the same error: "$.simpleWeather is not a function"

I've looking around, demos work fine but in my server it seems that not... here it's the last guide i followed:
http://www.jqueryscript.net/other/Simple-Weather-Plugin-with-jQuery-simpleWeather.html

All the files are in my webserver (they're accessible). I've read that Yahoo changed its API and the plugin is not working, is it related with my problem? Thanks!

**Comment by fleeting** [comment]
@legramo I would need to see a link to your site that is throwing the error. From the error though it sounds like you haven't included the simpleWeather script. It needs to be included before your `$.simpleWeather` code. You can either include the script from your server or use the CDN link in the readme.
